[doc] 자바스크립트 프로토타입 문서 작성
joshua1988/vue-camp pull request #113
Opened 2021-09-02 15:24 UTC by zwonlala

## 관련 이슈

#38 JS prototype

## 요약

빈 칸으로 되어 있던 prototype 문서를 작성해보았습니다.
리뷰 부탁드립니다 😄 

- prototype 개념 이해
- 프로토타입 체인
  - 메소드 오버라이드
  - 프로토타입 체이닝
- 자바스크립트 내장함수(?)

## 리뷰어

@yahma25 @mlsh1112

2021-09-02 15:29 UTC, zwonlala commented
프로토타입 개념이 다른 사람에게 바로 설명할 수 있을 정도로 잘 알고 있던 개념이 아닌 
대략적으로만 알고있던 내용이고 생각보다 쉽지 않은 내용이라 
내용을 파악하고 문서로 작성하는데 생각보다 오래 시간이 소요되었네요 🙏

위아래 있는 문서들은 보니 예상 독자가 자바스크립트에 대해 익숙하지 않은 분들인 것 같아 
어느 범위까지? 설명을 할 지와 이 개념을 어떻게 전달해야 할지 고민이 좀 있었습니다.

문서가 다른 문서에 비해 양이 좀 많은 것 같은 부분이 고민인데 날카로운 피드백 부탁드립니다! 😄

2021-09-02 15:46 UTC, zwonlala commented on docs/js/prototype.md
> +## 자바스크립트 내장함수
@joshua1988 
기효님 이 prototype 문서를 적기 전 다른 JS 관련 문서들이 어떤 느낌인지 보기위해 variable부터 쓱 보고 작업을 진행하였는데요

[String 문서](https://joshua1988.github.io/vue-camp/js/string.html#%E1%84%89%E1%85%AE%E1%86%BA%E1%84%8C%E1%85%A1%E1%84%8B%E1%85%AA%E1%84%8B%E1%85%B4-%E1%84%80%E1%85%AE%E1%84%87%E1%85%AE%E1%86%AB) 끝 부분에 **"자바스크립트 내장 함수(JavaScript Built-in API / JavaScript Native API)"** 에 대한 설명이 나와 있고, 자세한 내용은 이 프로토타입 문서에서 자세히 설명하겠다고 적혀 있었습니다.

"자바스크립트 내장 함수" 파트를 어떻게 설명해야 할지 좀 감이 안잡혀 검색을 해봤는데도 잘 모르겠는데
- 해당 부분을 위와 같이 소제목?(##)으로 뽑아서 설명을 하는 것과
- 위 설명 중에 해당 개념만 추가 설명하는 것

중에 어떤 방향으로 하는게 좋을 것 같으신가요?

2021-09-02 15:46 UTC, zwonlala commented on docs/js/prototype.md
> +- 모든 자바스크립트 객체들은 메서드와 속성들을 상속받기 위한 템플릿으로 프로토타입 객체(prototype object)를 가진다는 의미입니다.
이 부분의 두 li 는 '프로토 타입 기반 언어'를 설명하기 위해서 작성하다가 두 문장 중 어떤 문장이 더 좋은 것인지 고민이 되어 우선 둘 다 추가해보았습니다

문서를 다 작성하고 검색을 해보니 
두 번째 항목(`프로토타입 기반 언어에서는 어떤 객체를 원형(prototype)으로 삼고 이를 참조함으로써 상속과 비슷한 효과를 얻습니다`)이
 더 적절해 보이는데 어떻게 생각하시나요?

2021-09-03 12:31 UTC, zwonlala reviewed
prototype.md 추가한 img 에 설명 추가

2021-09-03 12:31 UTC, zwonlala commented on docs/js/prototype.md
> +![sadf](../../img/prototype_001.png)
이미지 추가하고 설명을 추가한다는 걸 깜빡했네요..! 

추후 피드백 받은 사항과 같이 커밋하여 올리겠습니다!

2021-09-03 12:31 UTC, zwonlala commented on docs/js/prototype.md
> +![sadf](../../img/prototype_001.png)
```suggestion
![simpleArray 출력 결과](../../img/prototype_001.png)
```

2021-09-03 12:31 UTC, zwonlala commented on docs/js/prototype.md
> +![](../../img/prototype_002.png)
```suggestion
![Array.prototype 출력 결과](../../img/prototype_002.png)
```

2021-09-03 12:31 UTC, zwonlala commented on docs/js/prototype.md
> +![](../../img/prototype_003.png)
```suggestion
![console.dir(simpleArray)의 결과](../../img/prototype_003.png)
```

2021-09-03 13:53 UTC, yahma25 reviewed
자바스크립트 근본 중 하나인 Prototype! 계속 화이팅이에요 💪

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +- 모든 자바스크립트 객체들은 메서드와 속성들을 상속받기 위한 템플릿으로 프로토타입 객체(prototype object)를 가진다는 의미입니다.
저도 두 번째 설명이 이해하기에 더 쉬워보이네요 😄

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +<br>
문서 전반에 걸쳐 줄바꿈 여백은 `<br/>` 1개씩만 사용해도 충분하지 않을까요? 🙄

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +브라우저의 개발자 도구에서 간단한 Array를 정의한 후 출력해보면 다음 화면과 같이 나옵니다. 출력된 결과를 보면 forEach, map, push와 같은 익숙한 함수들이 보입니다. 저희는 해당 함수를 정의하지 않았는데 그럼 어디에 해당 함수들이 정의되어 있고, 어떻게 해당 함수들을 쓸 수 있는 걸까요?
[개인 취향]
전개 순서를 아래와 같은 순서대로 하면 좀 더 읽기 자연스러울 것 같아요.

`... 다음 화면과 같이 나옵니다.`
[이미지]
`출력된 결과를 보면...`

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +브라우저의 개발자 도구에서 간단한 Array를 정의한 후 출력해보면 다음 화면과 같이 나옵니다. 출력된 결과를 보면 forEach, map, push와 같은 익숙한 함수들이 보입니다. 저희는 해당 함수를 정의하지 않았는데 그럼 어디에 해당 함수들이 정의되어 있고, 어떻게 해당 함수들을 쓸 수 있는 걸까요?
```suggestion
브라우저의 개발자 도구에서 간단한 Array를 정의한 후 출력해보면 다음 화면과 같이 나옵니다. 출력된 결과를 보면 forEach, map, push와 같은 익숙한 함수들이 보입니다. 우리는 해당 함수를 정의하지 않았는데 그럼 어디에 해당 함수들이 정의되어 있고, 어떻게 해당 함수들을 쓸 수 있는 걸까요?
```

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +브라우저의 개발자 도구에서 간단한 Array를 정의한 후 출력해보면 다음 화면과 같이 나옵니다. 출력된 결과를 보면 forEach, map, push와 같은 익숙한 함수들이 보입니다. 저희는 해당 함수를 정의하지 않았는데 그럼 어디에 해당 함수들이 정의되어 있고, 어떻게 해당 함수들을 쓸 수 있는 걸까요?
`해당 함수`가 한 문장에 연속적으로 3회 언급되고 있네요.
읽어보니 조금 어색하게 느껴지는데 바꿔보면 어떨까요? 😅

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +\_\_proto\_\_를 읽을 때는 'dunder proto'('던더 프로토')라고 읽으면 됩니다.
오호~ `dunder`  처음 알았네요. 배워갑니다 🤓

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +dunder는 'double underscore'의 줄임말
윗 문장보다 앞에 등장해도 좋을 것 같아요.
ex) dunder는 'double underscore'의 줄임말이며 `__proto__`를 읽을 때는 ...

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +위 예제에서 알아본 `__proto__` 와 `prototype` 프로퍼티의 관계가 바로 자바스크립트 프로토타입 개념의 핵심입니다. protype의 타입은 **객체**이고, prototype을 **참조**하는 \_\_proto\_\_ 또한 **객체**입니다. prototype 내부에는 **인스턴스가 사용할 메서드와 프로퍼티를 저장**합니다. 그럼 인스턴스
```suggestion
위 예제에서 알아본 `__proto__` 와 `prototype` 프로퍼티의 관계가 바로 자바스크립트 프로토타입 개념의 핵심입니다. prototype의 타입은 **객체**이고, prototype을 **참조**하는 \_\_proto\_\_ 또한 **객체**입니다. prototype 내부에는 **인스턴스가 사용할 메서드와 프로퍼티를 저장**합니다. 그럼 인스턴스에서 자동으로 생성한 \_\_proto\_\_ 프로퍼티를 통해 prototype 내부에 정의된 메서드와 프로퍼티를 사용할 수 있습니다.
```

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +### 메소드 오버라이드
```suggestion
### 메서드 오버라이드
```
일관성을 위하여 😄

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +인스턴스에서 생성자 함수의 prototype 프로퍼티를 참조하는 \_\_proto\_\_를 생략하면, 인스턴스는 prototype에 정의된 프로퍼티나 메소드를 자신의 것처럼 사용할 수 있다고 설명하였습니다. 그럼 만약 인스턴스에서 동일한 이름의 프로퍼티나 메서드를 가지고 있다면 어떨까요?
```suggestion
인스턴스에서 생성자 함수의 prototype 프로퍼티를 참조하는 \_\_proto\_\_를 생략하면, 인스턴스는 prototype에 정의된 프로퍼티나 메서드를 자신의 것처럼 사용할 수 있다고 설명하였습니다. 그럼 만약 인스턴스에서 동일한 이름의 프로퍼티나 메서드를 가지고 있다면 어떨까요?
```
일관성을 위하여 😄

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +`simpleArray` 인스턴스에 push 함수와 hasOwnProperty 함수를 정의하지 않았지만, 위와 같이 사용할 수 있는 이유는 자바스크립트 엔진이 메소드를 찾는 방식이 프로퍼티를 검색하고, 존재하지 않는다면 그다음으로 가까운 대상인 \_\_proto\_\_를 검색하는 순서로 진행하기 때문입니다. 위 예제에서 `console.dir(simple
```suggestion
`simpleArray` 인스턴스에 push 함수와 hasOwnProperty 함수를 정의하지 않았지만, 위와 같이 사용할 수 있는 이유는 자바스크립트 엔진이 메서드를 찾는 방식이 프로퍼티를 검색하고, 존재하지 않는다면 그다음으로 가까운 대상인 \_\_proto\_\_를 검색하는 순서로 진행하기 때문입니다. 위 예제에서 `console.dir(simpleArray);` 명령을 실행해보면, push 함수와 hasOwnProperty 함수가 어디에 정의되어 있는지 확인 할 수 있습니다.
```
일관성을 위하여 😄

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +\_\_proto\_\_ 와 [[Prototype]]
`__proto__`, `[[Prototype]]`과 같이 고유 키워드는 계속 `강조 표시`를 일관성 있게 하면 눈에 잘 들어올 것 같아요.
이 외에 대표 자바스크립트 키워드도요 😃

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +```
수학 증명식이 떠오르네요. 🤣  예시 설명 좋습니다 👍

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +정리하면, 자바스크립트는 함수에 자동으로 `prototype` 이라는 객체 타입의 프로퍼티를 생성합니다. new 연산자와 함께 함수를 호출할 경우, 즉 해당 함수를 생성자 함수로써 사용할 경우, 생성된 인스턴스에는 숨겨진 프로퍼티인 `__proto__` 프로퍼티가 자동으로 생성됩니다. 그리고 `__proto__` 프로퍼티는 생성자 함수의 `prototyp
...호출할 경우 ,`즉 해당 함수를 생성자 함수로써 사용할 경우,` 생성된 ...
뭔가 영문식 표현 같이 느껴졌어요 ㅎㅎ
`new 연산자를 이용하여 생성자 함수를 호출할 경우` 이런 식으로 줄여봐도 좋을 것 같네요 😉

2021-09-03 13:53 UTC, yahma25 commented on docs/js/prototype.md
> +ironMan.printName(); // I am Tony Stark
스포 당했다! 😲 🚀

2021-09-03 14:15 UTC, zwonlala commented on docs/js/prototype.md
> +<br>
문서의 내용이 많고 글이 길어 가독성을 위해 문장 사이에 br 태그를 의도적으로 좀 많이 넣었습니다 🙏 

일반적인 설명 중간중간에 한 꼭지가 끝나는 시점에는 br 태그를 하나

그리고 설명하는 내용이 바뀔때는 header의 레벨?(md 문법의 #의 개수) 에 따라 br 태그를 2,3개씩 추가했습니다

너무 많다고 생각되시면 줄여보도록 하겠습니다 

다른분들은 어떻게 생각하시나요?

2021-09-03 14:17 UTC, zwonlala commented on docs/js/prototype.md
> +브라우저의 개발자 도구에서 간단한 Array를 정의한 후 출력해보면 다음 화면과 같이 나옵니다. 출력된 결과를 보면 forEach, map, push와 같은 익숙한 함수들이 보입니다. 저희는 해당 함수를 정의하지 않았는데 그럼 어디에 해당 함수들이 정의되어 있고, 어떻게 해당 함수들을 쓸 수 있는 걸까요?
첨부한 이미지가 세로로 좀 길어서 위와 같이 문장이 끝나고 나서 이미지를 첨부했는데

생각해보니 명호님께서 조언해주신 대로 바로 이미지가 나오는게 더 이해하기 쉬울 것 같네요! 😀

2021-09-03 14:21 UTC, zwonlala commented on docs/js/prototype.md
> +브라우저의 개발자 도구에서 간단한 Array를 정의한 후 출력해보면 다음 화면과 같이 나옵니다. 출력된 결과를 보면 forEach, map, push와 같은 익숙한 함수들이 보입니다. 저희는 해당 함수를 정의하지 않았는데 그럼 어디에 해당 함수들이 정의되어 있고, 어떻게 해당 함수들을 쓸 수 있는 걸까요?
엇 그렇네요...😅🤣
계속 똑같은 문장을 계속 보다보니 어색한 걸 못느꼈네요

두번째와 세번째 '해당'은 빼도록하겠습니다! 

날카로운 지적 감사합니다 🙏

2021-09-03 14:23 UTC, zwonlala commented on docs/js/prototype.md
> +dunder는 'double underscore'의 줄임말
🤔 전 뒤에 오는게 더 자연스러운 것 같은데 다른 분들은 어떠신가요?

2021-09-03 14:24 UTC, zwonlala commented on docs/js/prototype.md
> +위 예제에서 알아본 `__proto__` 와 `prototype` 프로퍼티의 관계가 바로 자바스크립트 프로토타입 개념의 핵심입니다. protype의 타입은 **객체**이고, prototype을 **참조**하는 \_\_proto\_\_ 또한 **객체**입니다. prototype 내부에는 **인스턴스가 사용할 메서드와 프로퍼티를 저장**합니다. 그럼 인스턴스
엇 오타를 못찾았네요..... 🙏 
제보 감사합니다!

2021-09-03 14:26 UTC, zwonlala commented on docs/js/prototype.md
> +인스턴스에서 생성자 함수의 prototype 프로퍼티를 참조하는 \_\_proto\_\_를 생략하면, 인스턴스는 prototype에 정의된 프로퍼티나 메소드를 자신의 것처럼 사용할 수 있다고 설명하였습니다. 그럼 만약 인스턴스에서 동일한 이름의 프로퍼티나 메서드를 가지고 있다면 어떨까요?
아 네넵 윗 부분은 메소드로 먼저 적고 메서드로 고쳤는데

아래 부분은 수정하는 걸 깜빡했네용 🙏 

관련하여 헤더 부분도 메서드로 수정하겠습니다 😀

2021-09-04 06:18 UTC, daaaayeah commented on docs/js/prototype.md
> +dunder는 'double underscore'의 줄임말
명호님 의견도 좋은데, 저도 뒤에 오는 게 좀 더 자연스럽다고 생각해요🙂
먼저 dunder에 대해 알려주고 이를 언급하기보다는
dunder를 언급하고 뭔지 알려주는 게 흐름상 자연스럽게 읽힐 것 같아요.

`dunder는 'double underscore'의 줄임말`처럼
기존 문장과 구분 지어도 좋을 것 같고요!

2021-09-04 08:31 UTC, yahma25 commented on docs/js/prototype.md
> +dunder는 'double underscore'의 줄임말
다시보니 앞에 언급된 적이 없었네요~ 두 분 말씀에 동의합니다 😄

2021-09-04 12:56 UTC, zwonlala commented on docs/js/prototype.md
> +\_\_proto\_\_ 와 [[Prototype]]
이 부분을 저도 고민했었는데 `__proto__` 같은 경우 너무 빈번하게 사용되는 것 같아 
강조 표시를 코드 상에서 사용하였을때만 적용해보았습니다!

다른분들은 어떻게 생각하시나요?

2021-09-04 12:57 UTC, zwonlala commented on docs/js/prototype.md
> +정리하면, 자바스크립트는 함수에 자동으로 `prototype` 이라는 객체 타입의 프로퍼티를 생성합니다. new 연산자와 함께 함수를 호출할 경우, 즉 해당 함수를 생성자 함수로써 사용할 경우, 생성된 인스턴스에는 숨겨진 프로퍼티인 `__proto__` 프로퍼티가 자동으로 생성됩니다. 그리고 `__proto__` 프로퍼티는 생성자 함수의 `prototyp
```suggestion
정리하면, 자바스크립트는 함수에 자동으로 `prototype` 이라는 객체 타입의 프로퍼티를 생성합니다. new 연산자와 함께 함수를 호출하여 함수를 생성자 함수로써 사용할 경우, 생성된 인스턴스에는 숨겨진 프로퍼티인 `__proto__` 프로퍼티가 자동으로 생성됩니다. 그리고 `__proto__` 프로퍼티는 생성자 함수의 `prototype` 프로퍼티를 **참조** 합니다. `__proto__` 프로퍼티는 **생략이 가능** 하기 때문에 인스턴스에서 생성자 함수의 `prototype`에 정의된 메서드나 프로퍼티에 **접근** 할 수 있습니다.
```

이렇게 고쳐보겠습니다~ 😄

2021-09-08 13:18 UTC, joshua1988 commented on docs/js/prototype.md
> +## 자바스크립트 내장함수
@zwonlala 에고 지원님 제가 답변이 넘 늦었죠? 🥲 현재 올려주신 문서 기준으로는 참고 레벨의 목차로 빼야 할 것 같아요. 그리고 앞에 보니까 프로토타입 체이닝에 내장 함수가 설명되어 있는 것 같은데 요 부분에 간단하게 설명 추가해 주시는 게 좋을 것 같습니다 😄 그래야 글의 흐름이 어색하지 않을 것 같아요!

2021-09-08 13:21 UTC, joshua1988 commented on docs/js/prototype.md
> +\_\_proto\_\_를 읽을 때는 'dunder proto'('던더 프로토')라고 읽으면 됩니다.
저도 첨 알았습니다.. 재밌네요! ㅋㅋ 😄

2021-09-08 13:23 UTC, joshua1988 commented on docs/js/prototype.md
> +## prototye 개념 이해
```suggestion
## prototype 개념 이해
```

@zwonlala 지원님 그 "prototype 개념 이해"부터 다음 제목인 "프로토타입 체인"까지 너무 호흡이 긴 것 같아요. 중간에 소 제목들로 좀 더 짧게 나눠주시면 좋을 것 같습니다. 그리고 글의 첫 시작에서 프로토타입(prototype)이라고 설명해 주셨기 때문에 글 중간 중간에서 코드에 언급되는 사례 말고는 prototype을 그냥 프로토타입이라고 적어주셔도 될 것 같아요 😄

2021-09-08 13:25 UTC, joshua1988 requested changes
@zwonlala 지원님 일단 "프로토타입 체인" 이전까지 다시 한번 글을 정리해 보시면 좋을 것 같아요. 중요하고 꽤 무거운 주제인데 상세하게 글을 잘 적어주셨네요 😄 질문 주신거 답변 드렸고 피드백 몇 개 추가로 남겼습니다 😄 첫 컨트리뷰션 화이팅이에요! 👍 👍

2021-09-10 12:35 UTC, zwonlala commented on docs/js/prototype.md
> +## 자바스크립트 내장함수
@joshua1988 네넵 답변 감사합니다 기효님! 😃 

`현재 올려주신 문서 기준으로는 참고 레벨의 목차로 빼야 할 것 같아요.`
피드백 주신 부분 중에 위 부분이 이해가 잘 안되는데 혹시 추가적으로 설명해주실 수 있으신가요...? 🙏

2021-09-10 12:36 UTC, zwonlala commented on docs/js/prototype.md
> +<br>
@joshua1988 아 네넵 알겠습니다!
문단이 끝나고 다음 소제목이 나오면 br 태그나 줄바꿈 빼도록하겠습니다!

2021-09-10 12:41 UTC, zwonlala commented on docs/js/prototype.md
> +## prototye 개념 이해
엇 여기도 오타가 있었네요.... 🥲 
아 그렇네요...! [prototye 개념 이해] 부분 소제목으로 나눠보겠습니다!
prototype 으로 작성한 부분은 프로토타입으로 작성할게요!!

2021-09-10 13:12 UTC, zwonlala commented on docs/js/prototype.md
> +## prototye 개념 이해
@joshua1988  기효님 글 중간중간에 

**_프로토타입 개념_** 을 의미하는 prototpye은 한글로 "프로토타입"으로 변경하였고

**_prototype 프로퍼티_** 를 의미하는 prototype은 그대로 영어로 "prototype"으로 유지시켜놓겠습니다!!

2021-09-10 13:56 UTC, zwonlala commented on docs/js/prototype.md
> +## 자바스크립트 내장함수
@joshua1988 기효님 추가적으로 
자바스크립트 내장함수에 관해서 `요 부분에 간단하게 설명 추가해 주시는 게 좋을 것 같습니다 😄`라고 조언해주셨는데

```suggestion
그리고 위에서 설명한 push 함수와 hasOwnProperty 함수를 **`'자바스크립트 내장함수'`** 라고 합니다. 자바스크립트 내장함수는 Array와 Object와 같은 **`'자바스크립트 표준 내장 객체'`** 의 prototype에 정의되어 있는 함수입니다. 자세한 사항은 [MDN 표준 내장 객체](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects) 문서에 나온 객체 문서의 '인스턴스'나 '프로토타입' 부분을 참고해주세요.
```
위와 같이 작성하면 될까요?

2021-09-11 05:50 UTC, joshua1988 commented on docs/js/prototype.md
> +## 자바스크립트 내장함수
@zwonlala 오 네 지원님 설명 충분히 좋은 것 같습니다 😄 👍 👍 👍

2021-09-11 16:23 UTC, zwonlala commented on docs/js/prototype.md
> +## 자바스크립트 내장함수
@joshua1988 기효님 위 https://github.com/joshua1988/vue-camp/pull/113/files/f1f3331a3864d7a78121e938f736857d961d91e2#r706144601 코멘트 부분은 아직 이해가 잘 안가는데 다시 한번 설명 요청드려도 될까요?

2021-09-11 16:23 UTC, zwonlala commented on docs/js/prototype.md
> +### prototype 프로퍼티와 **proto** 프로퍼티
```suggestion
### prototype 프로퍼티와 **\_\_proto\_\_** 프로퍼티
```
앞뒤로 언더바를 추가하는 걸 깜빡했네요...!
최종 머지하기 전 해당 부분 수정하고 머지하겠습니다!

2021-09-27 11:01 UTC, zwonlala commented on docs/js/prototype.md
> +## 자바스크립트 내장함수
@joshua1988 기효님 나중에 확인하시면 위 https://github.com/joshua1988/vue-camp/pull/113/files/f1f3331a3864d7a78121e938f736857d961d91e2#r706144601 코멘트 부분 설명 한번만 부탁드립니다...!

2021-09-29 14:48 UTC, daep93 commented on docs/js/prototype.md
> +\_\_proto\_\_를 읽을 때는 'dunder proto'('던더 프로토')라고 읽으면 됩니다.
저도 처음 알았습니다 던더 프로토라니... 재밌네요 ㅎㅎ

2021-09-29 14:52 UTC, daep93 commented on docs/js/prototype.md
> +\_\_proto\_\_ 와 [[Prototype]]
저는 일관성 있게 쓰이는게 좋다고 생각합니다. 아니면 기울여쓰거나 강조하는 식으로 해서 다른 문장과 돋보이면 좋겠다고 생각합니다. 

추가적으로 이 warning 부분은 57번째 줄 뒤에 오면 더 좋을 것 같습니다. 앞에서 호기심을 불러일으켰는데 곧바로 워닝을 걸어버리면 읽는 흐름도 끊고 무슨 이야기 하는지 바로 이해할 수가 없을 것 같아요. 적어도 프로토타입이 정확히 뭔지 설명한 다음에 워닝을 붙이면 좋을 것 같습니다.

2021-09-29 14:57 UTC, daep93 commented on docs/js/prototype.md
> +자바스크립트는 **`프로토타입 기반 언어(prototype-based language)`** 입니다. 프로토타입 기반 언어에서는 어떤 객체를 원형(prototype)으로 삼고 이를 참조함으로써 상속과 비슷한 효과를 얻습니다. 자바스크립트의 프로토타입을 이해하기 위해서는 prototype 프로퍼티를 우선 이해해야 합니다. 간단한 예제로 시작해보겠습니다.
여러 문서에서 프로퍼티를 속성으로 표기하고 있기 때문에 이를 맞추면 좋을 것 같습니다.

2021-09-29 15:00 UTC, daep93 commented on docs/js/prototype.md
> +\_\_proto\_\_ 프로퍼티는 단지 브라우저에서 [[Prototype]]을 구현한 대상이며 권장되는 방식이 아닙니다. 최신 브라우저 개발자 도구에서는 \_\_proto\_\_가 아닌 [[Prototype]]으로 표현될 수 있습니다. 본 문서에서는 이해하기 쉽게 하기 위하여 설명과 사진에 \_\_proto\_\_ 프로퍼티를 사용하였습니다.
\_\_proto\_\_가 권장되는 방식이 아니라면 권장되고 있는 방식도 이어서 설명하면 좋을 것 같습니다.

2021-09-29 15:05 UTC, daep93 commented on docs/js/prototype.md
> +Person.prototype.printName = function() {
Person에 prototype을 정의하지 않았는데 왜 정의되어 있는지에 대해서는 코드 블록 아래 설명칸에 105번째 줄처럼 적어두면 좋을 것 같습니다.

2021-10-01 12:51 UTC, zwonlala commented on docs/js/prototype.md
> +\_\_proto\_\_ 와 [[Prototype]]
아 네넵 그럼 __proto__ 프로퍼티를 명시하는 부분은 **`__proto__`** 문법을 사용하여 일관성 있게 고쳐보겠습니다! 😄 

아 해당 warning을 저 위치에 위치시킨 이유는, 직전 예시가 개발자 도구로 배열을 출력해보는 예시인데,
최신 크롬 같은 경우에는 위 예시 사진 처럼 "__proto__" 가 나오는 것이 아니라 
"[[Prototype]]"으로 출력되어 헷갈릴 수 있을 것 같아 바로 명시를 해줬습니다..!

그런데 대현님 말씀대로 아직 프로토타입이 뭔지 잘 모르는데 warning 내용이 나오면 좀 혼란스러울 것 같기도 하네욥 🤔

2021-10-01 12:57 UTC, zwonlala commented on docs/js/prototype.md
> +자바스크립트는 **`프로토타입 기반 언어(prototype-based language)`** 입니다. 프로토타입 기반 언어에서는 어떤 객체를 원형(prototype)으로 삼고 이를 참조함으로써 상속과 비슷한 효과를 얻습니다. 자바스크립트의 프로토타입을 이해하기 위해서는 prototype 프로퍼티를 우선 이해해야 합니다. 간단한 예제로 시작해보겠습니다.
오 네넵 좋은 피드백 감사합니다! 😄

2021-10-01 13:08 UTC, zwonlala commented on docs/js/prototype.md
> +\_\_proto\_\_ 프로퍼티는 단지 브라우저에서 [[Prototype]]을 구현한 대상이며 권장되는 방식이 아닙니다. 최신 브라우저 개발자 도구에서는 \_\_proto\_\_가 아닌 [[Prototype]]으로 표현될 수 있습니다. 본 문서에서는 이해하기 쉽게 하기 위하여 설명과 사진에 \_\_proto\_\_ 프로퍼티를 사용하였습니다.
해당 부분을 처음 작성했을 때는 권장되는 방식에 대해 설명하였습니다.
그런데 Warning 부분 분량이 너무 길어지고,
예상되는 독자인 프로토타입 개념에 대해 잘 모르는 독자가 알기에는 조금 deep 한 내용이라는 생각이 들어 생략하게 되었습니다!

첨부한 참고 문서에 권장되는 방식이 나와있는데, 권장되는 방식은 하단의 참고 문서를 참고해달라는 내용 추가해놓겠습니다!!! 😄

2021-10-01 14:01 UTC, daep93 commented on docs/js/prototype.md
> +\_\_proto\_\_ 와 [[Prototype]]
@zwonlala 아...개발자 도구 예시가 최신 브라우저인줄 알고 헷갈렸습니다. 예시가 [[Prototype]]로 되어있다면 현재 위치에 warning이 와도 이해가 될 것 같습니다.

2021-10-10 13:06 UTC, joshua1988 commented on docs/js/prototype.md
> +## 자바스크립트 내장함수
@zwonlala 에고 지원님, 제가 코멘트 확인이 늦었네요. 많이 기다리셨죠? ㅜ 참고 레벨의 목차라는 의미는 아래 문서 정도를 의미한 건데요. 위에서 제안해 주신 내용 정도면 충분할 것 같아요 😄 

![image](https://user-images.githubusercontent.com/3272748/136697047-8510b466-2b69-4998-a6bc-af3ceffc6086.png)

2021-10-11 23:09 UTC, zwonlala commented on docs/js/prototype.md
> +## 자바스크립트 내장함수
@joshua1988 네넵 알겠습니다 기효님!! 답변 감사드려요!!!

2021-10-11 23:31 UTC, merged