[doc] 컴포넌트 네비게이션 가드 설명 및 가드 호출 순서 설명 추가 #35
joshua1988/vue-camp pull request #115
Opened 2021-09-03 16:05 UTC by daep93

#35 이슈를 반영해서 문서에 컴포넌트 가드 설명을 추가하였습니다.

추가한 부분은 크게 아래와 같습니다.
1. 네비게이션 가드 정의
2. 컴포넌트 네비게이션 가드 설명 전반
3. 네비게이션 가드 호출 순서

그 외로 전역 가드와 지역 가드의 정의를 추가해뒀습니다. 컴포넌트 네비게이션 가드 부분은 [기효님 블로그](https://joshua1988.github.io/web-development/vuejs/vue-router-navigation-guards/)를 참조했고, 구체적인 사용법을 찾기 위해서 [Vue-Router](https://router.vuejs.org/guide/advanced/navigation-guards.html)를 참조하였습니다.
 
리뷰 부탁드리겠습니다! 감사합니다!😄 😄 😄

2021-09-05 10:33 UTC, jm-chong approved these changes
수고 많으셨습니다. 👍

2021-09-05 10:33 UTC, jm-chong commented on docs/advanced/navigation-guard.md
> +## 참고 자료
오. .참고자료 추가 너무 좋습니다. 👍

2021-09-05 10:33 UTC, jm-chong commented on docs/advanced/navigation-guard.md
next 는 꼭 호출되어야 하므로, `warning` 으로 강조되어도 좋을것 같습니다.

2021-09-05 10:33 UTC, jm-chong commented on docs/advanced/navigation-guard.md
>  ## 네비게이션 전역 가드
전역가드, 지역가드 로만 표시되어도 충분할것 같습니다.

2021-09-05 10:36 UTC, daep93 commented on docs/advanced/navigation-guard.md
넵, 피드백 반영해두겠습니다! 감사합니다.

2021-09-05 10:37 UTC, daep93 commented on docs/advanced/navigation-guard.md
>  ## 네비게이션 전역 가드
@jm-chong 컴포넌트 가드를 전역, 지역으로 나누고 지역에서 라우트 별 가드랑 컴포넌트 가드로 나눠 설명하라는 말씀이실까요?

2021-09-05 10:52 UTC, jm-chong commented on docs/advanced/navigation-guard.md
>  ## 네비게이션 전역 가드
```
## 네비게이션 가드 종류
### 전역 가드
### 지역 가드
```

이런식으로 되면 어떨까요? ㅎ

2021-09-05 10:54 UTC, daep93 commented on docs/advanced/navigation-guard.md
>  ## 네비게이션 전역 가드
@jm-chong 아... 제가 착각을 했습니다. 헤더를 말씀하신거군요! 반영하겠습니다. 감사합니다.

2021-10-03 07:10 UTC, scl2589 commented on docs/advanced/navigation-guard.md
> +`next('/')`: 라우트 우회
라우트 우회라는 말을 조금 더 풀어서 설명해주시면 좋을 것 같습니다! 
next 함수의 인자에 `'/'`이외에도 `router-link`의 `to`나 `router-push`에서 사용되는 옵션들 (name: 'home' 등) 도 사용될 수도 있다는 점도 같이 추가해주시면 next를 통해 다른 라우터로 이동할 수 있다는 부분을 쉽게 이해할 수 있을 것 같습니다.

2021-10-04 04:48 UTC, daep93 commented on docs/advanced/navigation-guard.md
> +`next('/')`: 라우트 우회
그렇군요, name 속성을 명시해서 라우트 이동이 가능한지 몰랐습니다. 알려주신 부분 반영해서 수정하도록 하겠습니다 ㅎㅎ 감사합니다.

2021-10-04 04:53 UTC, daep93 commented on docs/advanced/navigation-guard.md
>  전역 가드는 모든 라우팅에 적용되는 네비게이션 가드입니다. 아래는 전역 가드를 설정하는 코드입니다.
@scl2589 라우팅은 라우터를 이용해서 이동하는 방식을 뜻하는 것으로 문서에서는 라우터를 통해 이동하는 방식에 전역가드가 모두 적용될 수 있다는 뜻으로 적어뒀습니다.

`beforeEach` 부분은 제가 적은 부분이 아니지만 우선 채린님 말씀대로 반영을 해서 기효님께 변경 승인을 받겠습니다.

2021-10-10 10:46 UTC, joshua1988 requested changes
@daep93 👍 👍

2021-10-17 00:37 UTC, merged