[doc] 자바스크립트 옵셔널 체이닝 문서 작성
joshua1988/vue-camp pull request #116
Opened 2021-09-03 16:42 UTC by shinyuna

## 관련 이슈

#107 

## 요약

자바스크립트의 옵셔널 체이닝 문법에 대해서 문서를 작성했습니다. 
부족한 부분 피드백 주시면 반영하겠습니다 감사합니다 :)

## 리뷰어

2021-09-04 06:19 UTC, daep93 commented on docs/es6+/optional-chaning.md
> +옵셔널 체이닝으로 객체의 속성 값을 확인하고 `undefined` 가 반환되면 널 병합 연산자(`??`)를 통해 기본 값을 제공할 수 있습니다.
유나님 덕분에 옵셔널 체이닝이 무엇인지 알게 되었습니다. 감사합니다 👍 
한 가지만 피드백 드리자면 널 병합 연산자를 다룬 설명 페이지가 있는데, 그 부분을 링크 걸어주시면 더 좋을 것 같습니다 😄

2021-09-04 14:12 UTC, shinyuna commented on docs/es6+/optional-chaning.md
> +옵셔널 체이닝으로 객체의 속성 값을 확인하고 `undefined` 가 반환되면 널 병합 연산자(`??`)를 통해 기본 값을 제공할 수 있습니다.
오 대현님 감사합니다 :)

2021-09-05 10:22 UTC, jm-chong approved these changes
옵셔널 체이닝에 대해 잘 이해할 수 있을것 같습니다.

1. optional Channing 이 지원되는 ES2020 버전에 대해 언급이 되면 좋겠습니다.
2. 
대현님도 말씀주셨지만, 
optional chaning과 nullish colaesing이 한 문서로 같이 언급되어도 좋겠다는 생각도 드네요
나중에는 두 문서를 합쳐서 함께 설명되면 어떨지 제안 드립니다.

2021-09-05 10:22 UTC, jm-chong commented on docs/es6+/optional-chaning.md
> +옵셔널 체이닝을 사용하면 이전 코드보다 좀 더 깔끔하게 중첩된 객체의 하위 속성 값에 접근할 수 있습니다.
문법적인 깔끔함 + 안전하게 객체에 접근할 수 있는 내용도 추가되면 좋을것 같습니다.

2021-09-05 10:22 UTC, jm-chong commented on docs/es6+/optional-chaning.md
> +userInfo.userInfo?.()
문맥상 
```
userInfo.getInfo?.()
```
가 맞을것 같습니다..

2021-09-05 11:00 UTC, shinyuna commented on docs/es6+/optional-chaning.md
> +userInfo.userInfo?.()
헉... 수정하겠습니다 감사합니다!

2021-09-05 13:12 UTC, yooseongsil commented
@shinyuna 유나님 **textbook.md**쪽에도 es6+로 고쳐주시면 더 통일성이 있을 것 같아요😄
```
### 📖 입문

- [자바스크립트 기본](/js/variable.html)
- [ES6](/es6/const-let.html) 👉 13라인이요!
- [Vue.js 기본](/vue/instance.html)
```

2021-09-10 00:10 UTC, daehyun-thevc commented on docs/.vuepress/config.js
> +            children: ['/d3/d3', '/d3/vue-with-d3', '/d3/tutorial'],
유나님, 사소한거긴한데 es6+와 관련이 없는 D3의 설정이 내용변화없이 포맷만 바뀌었습니다. 혹시 prettier를 통해 저장하면서 동시에 리포매팅하고 계시나요? 이렇게 의도적이지 않은 변경은 다른 분들 pr에 영향을 미칠 수 있습니다. 아직 prettier 관련 설정이 PR되지 않았기 때문에 그 전까지는 prettier를 끄고 저장해주시면 좋을 것 같습니다.

2021-10-10 11:30 UTC, joshua1988 commented on docs/es6+/optional-chaning.md
> +	...
유나님 요고 다른 코드의 인덴팅이랑 맞춰서 정리되면 좋을 것 같아요 😄

2021-10-10 11:30 UTC, joshua1988 commented on docs/es6+/optional-chaning.md
> +	}
요기도..! 😄

2021-10-10 13:01 UTC, joshua1988 requested changes
@shinyuna 유나님 글 잘 봤습니다. 실무에서 유용한 문법을 잘 추가해 주셨네요 😄  피드백 남긴거 보시고 의견 있으시면 알려주세요~ 😄  👍 👍 👍

2021-10-10 13:01 UTC, joshua1988 commented on docs/es6+/optional-chaning.md
> +옵셔널 체이닝을 남용하지 않도록 주의해주세요.
왜 옵셔널 체이닝을 남용하면 안되는지에 대한 간략한 설명이 추가되면 좋을 것 같아요!

2021-10-20 13:41 UTC, merged