[doc] 자바스크립트 널 병합 연산자(Nullish coalescing operator) 활용 가이드 제작
joshua1988/vue-camp pull request #26
Opened 2021-08-11 15:50 UTC by shinyuna

## 관련 이슈

## 요약

안녕하세요.
자바스크립트의 널 병합 연산자(Nullish coalescing operator)에 대해서 문서화 했습니다!
널리쉬 콜레싱 오퍼레이터라고 쓰기엔 조금 길고 어색해서 한글로 번역한 널 병합 연산자라고 작성했습니다.
피드백 주시면 반영하겠습니다. 
감사합니다 :)

## 리뷰어

2021-08-12 13:11 UTC, yahma25 commented on docs/es6/nullish-coalescing-operator.md
> +function printTitle(text) {
[제안] input, ouput도 같이 명시해주면 좀 더 직관적으로 이해하는데 도움이 되지 않을까요? 😃 

ex)
```javascript
function printTitle(text) {
  let title = text;
  if (text == null || text == undefined) {
    title = 'Cracking Vue.js';
  }
  console.log(title);
}
printTitle('Crack'); // "Crack"
printTitle(); // "Cracking Vue.js"
```

2021-08-12 13:14 UTC, yahma25 commented on docs/es6/nullish-coalescing-operator.md
> +## 논리 연산자 OR(||)와의 차이점
[제안] 연산자에 강조 효과를 넣어주면 좀 더 눈에 띄어 읽기 편할 것 같아요. 😺 

ex) OR(`||`)

2021-08-12 13:16 UTC, shinyuna commented on docs/es6/nullish-coalescing-operator.md
> +## 논리 연산자 OR(||)와의 차이점
오 피드백 감사합니다!!ㅎㅎ
반영하도록 할게요 :)

2021-08-12 16:05 UTC, joshua1988 requested changes
@shinyuna 고생 많으셨습니다 유나님 😄 이렇게 적극적으로 빠르게 PR을 올려주시다니 넘 좋네요! 글 잘 봤습니다. 앞으로도 많은 활동 기대할게요 😄

2021-08-12 16:05 UTC, joshua1988 commented on docs/es6/nullish-coalescing-operator.md
> +하지만 논리 연산자 OR(`||`)는 null과 undefined를 포함한 falsy 한 값인 `0`, `''`, `NaN`의 경우에도 왼쪽 피연산자를 반환합니다.
```suggestion
하지만 논리 연산자 OR(`||`)는 null과 undefined를 포함한 falsy 한 값인 `0`, `''`, `NaN`의 경우에도 오른쪽 피연산자를 반환합니다.
```

@shinyuna 요렇게 오른쪽이라고 해야 앞의 문장과 뜻이 통하는 것 같은데 제 추측이 맞을까요? 😄

2021-08-12 16:15 UTC, shinyuna commented on docs/es6/nullish-coalescing-operator.md
> +널 병합 연산자(Nullish coalescing Operator)는 연산자(`??`)의 왼쪽 피연산자가 null 또는 undefined일 때 오른쪽 피연산자를 반환하고, 그렇지 않으면 왼쪽 피연산자를 반환하는 논리 연산자입니다.
ㅋㅋㅋㅋ 코멘트 보다가 터졌습니당.. 유머 감각까지 완벽하신 기효 멘토님 👍

2021-08-12 16:16 UTC, shinyuna commented on docs/es6/nullish-coalescing-operator.md
> +하지만 논리 연산자 OR(`||`)는 null과 undefined를 포함한 falsy 한 값인 `0`, `''`, `NaN`의 경우에도 왼쪽 피연산자를 반환합니다.
앗 맞습니다!! 저런 실수를 하다닛..ㅜㅜ

2021-08-12 16:27 UTC, amorfati0310 reviewed
@shinyuna님 안녕하세요 수고많으셨습니다 
지금은 es6 폴더 항목에 들어가 있는데 
최신 문법들 소개하는 부분은
esNext로 새롭게 만들어서 넣어주시는게 더 좋을 것 같네요

2021-08-12 16:27 UTC, amorfati0310 commented on docs/es6/nullish-coalescing-operator.md
> +  }
단락에서 한 칸 띄어주면 더 가독성이 좋을 것 같아요

2021-08-12 16:27 UTC, amorfati0310 commented on docs/es6/nullish-coalescing-operator.md
> +# 널 병합 연산자(Nullish coalescing Operator)
```suggestion
#  Nullish coalescing Operator (??)
```
?? 연산자가 제목에 들어가면 더 좋을 것 같습니다.
- [참고 mdn 문서]( https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator)

2021-08-12 16:27 UTC, amorfati0310 commented on docs/es6/nullish-coalescing-operator.md
> +}
함수 선언 한 후 한 칸 띄어주면 더 좋을 것 같습니다.

2021-08-12 16:27 UTC, amorfati0310 commented on docs/es6/nullish-coalescing-operator.md
> +:::tip
```suggestion
> TIP:
```

2021-08-12 16:27 UTC, amorfati0310 commented on docs/es6/nullish-coalescing-operator.md
> +function getDemeritCount(count) {
역할이 단순이 카운트를 return 하는 함수여서 printTitle 처럼  좀 더 간단한 함수명으로 getCount 로 변경하는게 어떨까요? 
```suggestion
function getCount(count) {
```

2021-08-12 16:27 UTC, amorfati0310 commented on docs/es6/nullish-coalescing-operator.md
> +하지만 논리 연산자 OR(`||`)는 null과 undefined를 포함한 falsy 한 값인 `0`, `''`, `NaN`의 경우에도 왼쪽 피연산자를 반환합니다.
```suggestion
하지만 논리 연산자 OR(`||`)는 null과 undefined를 포함한 [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) 한 값인 `0`, `''`, `NaN`의 경우에도 왼쪽 피연산자를 반환합니다.
```

js에서 fasly 값의 링크를 걸어주면 더 좋을 것 같습니다.

2021-08-12 16:27 UTC, amorfati0310 commented on docs/es6/nullish-coalescing-operator.md
> +function printTitle(text) {
> || 를 defaultValue 로 활용하였을 때 문제
` `0`, `''`, `NaN` 과 같은 값을 유효한 값이라고 생각한 경우에는 문제가 발생합니다`
?? 로 이러한 문제를 해결할 수 있다. 
이런 흐름에 문구가 들어가면 더 좋을 것 같습니다.

2021-08-13 16:11 UTC, shinyuna commented on docs/.vuepress/config.js
> +  },
감사합니다 멘토님! 
esNext 폴더를 만드는 부분은 다른 분들의 의견도 함께 듣고 반영하도록 하겠습니다. :)

2021-08-14 07:41 UTC, joshua1988 commented
> @shinyuna님 안녕하세요 수고많으셨습니다
> 지금은 es6 폴더 항목에 들어가 있는데
> 최신 문법들 소개하는 부분은
> esNext로 새롭게 만들어서 넣어주시는게 더 좋을 것 같네요

요거 좋은 의견 주신 것 같아요 희찬님 좌측 메뉴 이름을 ES6+ 로 변경하든지 별도의 esNext 메뉴를 만들지는 한번 다른 분들과 같이 고민해 보면 좋을 것 같습니다 😄

2021-08-14 07:47 UTC, joshua1988 commented on docs/es6/nullish-coalescing-operator.md
> +:::tip
@amorfati0310 엇 희찬님 이건 blockquote 태그로 제안하신건가요? 유나님이 뷰 프레스에서의 tip 문법을 의도적으로 쓰신거 같던데 ㅎㅎ

[뷰프레스 tip 문법](https://v1.vuepress.vuejs.org/guide/markdown.html#custom-containers)

2021-08-14 07:48 UTC, joshua1988 approved these changes
@shinyuna 고생 많으셨습니다 유나님 적극적인 참여 감사드려요 😄

2021-08-14 09:19 UTC, amorfati0310 commented on docs/es6/nullish-coalescing-operator.md
> +:::tip
앗 뷰프레스 문법으로 그대로 남겨두는게 더 좋을 것 같네요 👍

2021-08-14 11:05 UTC, amorfati0310 approved these changes
수고하셨습니다 
제가 markdown 문법으로만 보고 고쳐달라고 한 부분 다시 vue press에 맞게 적용해주시면 더 좋을 것 같습니다 👍

2021-08-16 06:13 UTC, amorfati0310 commented
@shinyuna 님 충돌 파일이 있어서 머지가 안되는데 충돌해결 부탁드릴게요 ~~

2021-08-16 07:48 UTC, merged