[doc] DOC_CONTRIBUTION_GUIDE.md 마크다운 문법 출력 오류 수정
joshua1988/vue-camp pull request #54
Opened 2021-08-18 14:59 UTC by sewonkimm

## 요약

기존에 다음과 같이 生마크다운으로 나오던 표기를 bold 적용되도록 수정했습니다.

### 수정 내용

![image](https://user-images.githubusercontent.com/30452963/129921340-af5be046-5558-4ee6-8a69-21cf2a440ff1.png)

마크다운 문법이 중첩되어서 이런 현상이 발생한 것 같아요!

2021-08-19 12:17 UTC, amorfati0310 approved these changes

2021-08-19 12:17 UTC, amorfati0310 commented on .github/DOC_CONTRIBUTION_GUIDE.md
> +문서 작성 중간에 이해를 돕는 이미지를 삽입하고 싶은 경우 마크다운 문법의 <b>! [] ()</b>를 활용합니다.
```suggestion
문서 작성 중간에 이해를 돕는 이미지를 삽입하고 싶은 경우 마크다운 문법의 ```![]()```를 활용합니다.
```
코드 블락으로 주셔도 괜찮을 것 같네요 세원님 수고 많으셨습니다. ~~

2021-08-19 13:00 UTC, joshua1988 requested changes

2021-08-19 13:00 UTC, joshua1988 commented on .github/DOC_CONTRIBUTION_GUIDE.md
> +문서 작성 중간에 이해를 돕는 이미지를 삽입하고 싶은 경우 마크다운 문법의 <b>! [] ()</b>를 활용합니다.
@amorfati0310 코드 블락이 좋을 것 같네요! 😄

2021-08-19 14:12 UTC, sewonkimm commented
제안해 주신 대로 코드블록으로 대체하였습니다! 리뷰 감사합니다~

2021-08-22 09:45 UTC, joshua1988 approved these changes
@sewonkimm 오 세원님 첫 컨트리뷰션 축하드려요! 꼼꼼하게 확인하고 수정해 주셔서 감사합니다 😄

2021-08-22 09:45 UTC, merged