[doc] axios.md 설명 보충
joshua1988/vue-camp pull request #63
Opened 2021-08-21 15:07 UTC by scl2589

## 관련 이슈

#49 [doc] axios 설명 보충

## 요약

axios에 대한 설명을 보충하기 위해 아래 내용 추가하였습니다. 

- then, catch에 대한 설명 
- axios HTTP 메소드

2021-08-28 01:05 UTC, scl2589 commented on docs/vue/axios.md
> +- `patch`의 경우, 데이터의 일부를 교체할 경우에 사용됩니다.
기타 HTTP 요청 메소드는 빼기로 결정했습니다! :) 
멘토님 말씀대로 자주 사용하는 메소드를 위주로 설명하는 것이 좋은 것 같습니다.

2021-08-28 01:20 UTC, scl2589 commented
1. comment로 남겨주신 대로 문장 간결화
2. Put 수정
 참고자료는 다음과 같습니다.
 - [w3]([https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html))
 - [mdn](https://developer.mozilla.org/ko/docs/Web/HTTP/Methods/PUT)
3. Config 옵션 추가
- Config 옵션의 경우, axios 공식문서에서 참고하였습니다.
- [axios Request Config](https://axios-http.com/docs/req_config)

2021-08-28 01:21 UTC, scl2589 commented on docs/vue/axios.md
> +특정 데이터를 수정할 때 요청하는 메소드입니다. `put` 은 데이터 전체를 교체할 경우에 사용됩니다.
> @scl2589 `put`이 데이터 전체를 교체한다는 표현은 수정이 필요할 것 같아요 😄 HTTP PUT 메서드에서 대해서 더 알아보고 요 부분 고쳐보시면 좋을 것 같습니다 😄

이 부분 MDN과 w3 를 참고하여 수정했는데 제가 작성한 부분이 맞는지 한 번 더 확인 부탁드립니다 :)

2021-08-28 01:23 UTC, scl2589 commented on docs/vue/axios.md
> +서버에서 데이터를 가져올 때 사용하는 메소드입니다. 두번째 인자인 config 객체에는 헤더 (header), 응답초과시간 (timeout), 인자값 (params) 등의 요청값을 같이 넘길 수 있습니다.
> @scl2589 config 객체에 넘길 수 있는 옵션이 더 많은데 이 부분에 대한 언급을 더 해주면 좋겠고 추가로 옵션을 볼 수 있는 링크도 같이 인라인으로 추가되면 좋을 것 같습니다 😄

Axios 공식 문서의 [Request Config 문서](https://axios-http.com/docs/req_config)를 참고하여, 사용할만한 옵션을 추가하였습니다. 제가 현업에서 어떤 요청들이 주로 많이 쓰이는지는 잘 몰라 혹시 더 추가하면 좋은 config나 잘 안쓰이는 config가 있다면 추가적으로 수정해보겠습니다 👍

2021-08-28 01:28 UTC, scl2589 commented on docs/vue/axios.md
> +또한, `error.request`는 요청이 이루어졌으나, 응답을 받지 못한 경우를 뜻합니다. 즉, `request`는 `undefined` 상태로 이어지다, 서버에 성공적으로 요청이 이루어지면, 값이 설정됩니다. 만약 `request`가 `undefined` 라고 나타나면, 서버에 요청을 보내기도 전에 클라이언트 측에서 에러가 발생했다는 것을 뜻합니다.
@joshua1988 @jm-chong 넵, 혹시나 더 자세한 부분이 있을까 찾아보던 차에 Handling Errors를 참조하였습니다!  사실 저도 개발할 때 response 정도만 사용해봤는데 request는 처음 보는 방법이었습니다..ㅎㅎ 이 부분은 아예 제거하고 가는게 나을까요?

2021-08-28 01:29 UTC, scl2589 commented on docs/vue/axios.md
> +### .then
> 요렇게 대제목 하나 들어가면 좋을 것 같아요 😄

저도 제목이 있었으면 좋겠다고 생각했는데.. 깔끔한 제목 추천 감사합니다! 😃

2021-08-28 01:30 UTC, scl2589 commented on docs/vue/axios.md
> +자주 쓰이는 메소드는 get, post, put, delete입니다.
확실히 문장이 간결하네요 ㅎㅎ 피드백 반영해두었습니다! 감사합니다~

2021-08-28 01:30 UTC, scl2589 commented on docs/vue/axios.md
> +새로운 값이나 데이터를 추가할 때 사용하는 메소드입니다. 데이터와 함께 보내 새로운 값을 입력합니다.
피드백 감사합니다! 반영해두었습니다 :)

2021-08-28 01:31 UTC, scl2589 commented on docs/vue/axios.md
> +  .then(res => {
넵 ㅎㅎ `then`, `catch` 코드들이 반복되다 보니 불필요하겠다는 생각도 했었는데.. 피드백 감사합니다!

2021-08-28 03:46 UTC, yahma25 commented on docs/vue/axios.md
> +또한, `error.request`는 요청이 이루어졌으나, 응답을 받지 못한 경우를 뜻합니다. 즉, `request`는 `undefined` 상태로 이어지다, 서버에 성공적으로 요청이 이루어지면, 값이 설정됩니다. 만약 `request`가 `undefined` 라고 나타나면, 서버에 요청을 보내기도 전에 클라이언트 측에서 에러가 발생했다는 것을 뜻합니다.
[의견]
`오류를 처리하는 방법에는 response와 request로 나뉩니다.` 라고 하셨으니 예시가 있으면 좋을 것 같아요.
ex) `response`로 처리하는 사례와 `request`로 처리하는 사례

또는 오류를 처리하는 방법이 아닌 `error 객체에서 확인할 수 있는 주요 정보를 설명한다`는 관점에서
`response`, `request` 두 가지 정보가 대표적으로 있고 이 중에서 오류 처리를 위해 몇 가지 정보를 소개하는 식으로 끝낼 수도 있겠네요. 😉 

ps. 물론 저도 실무에선 `response`만 다뤄왔습니다. 😄

2021-08-29 08:23 UTC, amorfati0310 approved these changes
안녕하세요 채린님 axios 처음 보시는 분들이 살펴보기 좋겠네요 
수고 많으셨습니다 ~~

2021-09-01 12:49 UTC, scl2589 commented on docs/vue/axios.md
> +또한, `error.request`는 요청이 이루어졌으나, 응답을 받지 못한 경우를 뜻합니다. 즉, `request`는 `undefined` 상태로 이어지다, 서버에 성공적으로 요청이 이루어지면, 값이 설정됩니다. 만약 `request`가 `undefined` 라고 나타나면, 서버에 요청을 보내기도 전에 클라이언트 측에서 에러가 발생했다는 것을 뜻합니다.
89a789a96ad2d5171574df776fe9809bde0a3a0c 위 내용 조금 더 간결하게 수정하였습니다~

2021-09-01 12:50 UTC, scl2589 commented on docs/vue/axios.md
> +axios.get('통신할 서버주소')
감사합니다! :)
제시해주신 부분 추가하였습니다.

2021-09-01 15:00 UTC, joshua1988 requested changes
@scl2589 채린님 지난번에 드렸던 피드백 충실히 잘 반영하셨네요. 고생 많으셨어요 😄 몇 가지 추가로 피드백 남겼는데 한번 살펴보시고 궁금한 건 알려주세요. 그리고 문서 작성하시고 나서 다시 퇴고하시면 좀 더 가독성 높은 글이 나올 수 있을 것 같습니다. 전반적으로 약간 문서를 그냥 번역한 번역체 느낌이 좀 있어서 요걸 다시 몇 번 읽어보시면 자연스러운 글로 바꿔보실 수 있을거예요 😄 그리고 마지막에는 저희 문서 컨벤션 가이드 맞춰서 제대로 문서가 작성이 되었는지 확인해 보시면 좋을 것 같아요! 고생 많으셨습니다 😄

2021-09-02 14:28 UTC, scl2589 commented on docs/vue/axios.md
> +    catch(function (error) {
넵 맞습니다 ! 제가 더블체크 했어야 했는데..ㅎㅎ 수정하겠습니다!

2021-09-02 14:31 UTC, scl2589 commented on docs/vue/axios.md
> +서버에서 데이터를 가져올 때 사용하는 메소드입니다. 두번째 파라미터 `config` 객체에는 헤더 (header), 응답초과시간 (timeout), 인자값 (params) 등의 요청값을 같이 넘길 수 있습니다.
@joshua1988 넵! commit 하기 전에 전체적으로 확인하고 진행하겠습니다 :)

2021-09-02 14:32 UTC, scl2589 commented on docs/vue/axios.md
> +### method
@joshua1988 이 부분은 그럼 삭제하겠습니다!

2021-09-02 15:12 UTC, scl2589 commented
@joshua1988 피드백 너무 감사합니다! 확실히 제 글은 번역체 느낌이 있는데, 피드백 주신 글들은 자연스럽고 또 사용자가 읽기 더 편하네요! :)  
앞으로는 조금 더 쉽게 작성할 수 있도록 고민하고 작성하겠습니다. 마지막으로 맞춤법 검사기를 통해 맞춤법도 확인하였습니다.

2021-09-04 16:35 UTC, daep93 commented on docs/vue/axios.md
> +HTTP 통신이 성공했다는 뜻으로, `.then()`으로 결과값을 받아서 처리할 수 있습니다.
안녕하세요, 채린님. 멘티 박대현입니다. 엑시오스에 대해서는 저도 평소에 정리하고 싶을 정도로 복잡한 개념인데 미리 정리해주셔서 정말 감사하게 생각합니다. 저도 부족하지만 힘을 더해보고자 몇자 남깁니다.

.then을 HTTP 통신이 성공했다는 뜻으로 받아들이기에는 조금 설명의 핀트가 엇나간 것 같이 느껴집니다. 비동기 통신이 성공했을 경우 then에 넘겨준 콜백이 동작한다를 중점적으로 설명하면 어떨까 싶습니다. 아래처럼 비슷하게 적는건 어떨까요?
```
엑시오스 인스턴스의 then 메소드는 HTTP 통신이 성공할 경우 결과값을 처리할 수 있는 콜백을 인자로 받습니다. 
```

2021-09-05 05:56 UTC, amorfati0310 commented
안녕하세요 채린님 한 번 확인해보시고 merge 하셔도 좋을 것 같아요 👍

2021-09-05 07:15 UTC, scl2589 commented on docs/vue/axios.md
> +HTTP 통신이 성공했다는 뜻으로, `.then()`으로 결과값을 받아서 처리할 수 있습니다.
안녕하세요 대현님~ 수정해보겠습니다 피드백 감사합니다 :)

2021-09-05 07:27 UTC, merged