[doc] ES6 Destructuring - 뷰에 적용하는 구조 분해 문법 문서 작성
joshua1988/vue-camp pull request #66
Opened 2021-08-22 09:10 UTC by padosum

## 관련 이슈
#39  

## 요약
ES6 Destructuring 문서에 '뷰에 적용하는 구조 분해 문법' 활용 예시 추가하였습니다.

2021-08-22 13:36 UTC, jm-chong commented on docs/es6/destructuring.md
> +<li v-for="{ title, author, id } in posts" :key="id">
오... 이거 많이쓰는데 좋네요 👍

2021-08-22 13:39 UTC, jm-chong approved these changes
Vue 실무에서 많이쓰는 구조분해문법에 대해서 잘 설명해주셨네요.
수고하셨습니다.  💯

2021-08-22 14:15 UTC, amorfati0310 approved these changes
안녕하세요 연정님 수고 많으셨습니다 ~~ 👍

2021-08-23 02:24 UTC, padosum commented on docs/es6/destructuring.md
> +      fetchData(id);
피드백 감사드립니다! 예시 코드 수정하였습니다 😊

2021-08-31 02:09 UTC, padosum commented on docs/es6/destructuring.md
> +위 코드를 살펴보면 `this`를 매번 입력하지 않아도 되는 이점과 더불어 코드에서 어떤 데이터와 기능(function 등)만을 사용하는지 명확하게 파악할 수 있습니다. 그러므로 코드 작성자의 의도를 더 잘 설명해줍니다.
a68f9a2 에 회고 때 의견 주신 내용을 반영해보았습니다!

2021-09-01 15:04 UTC, joshua1988 requested changes
@padosum 연정님 회고 때 나온 얘기를 잘 반영해 주셨네요 😄 마지막으로 피드백 1개 있는데 요것만 수정하면 바로 PR 머지해도 될 것 같습니다 😄

2021-09-01 15:04 UTC, joshua1988 commented on docs/es6/destructuring.md
> +      savePost(id);
```suggestion
this.savePost(this.id);
```

@padosum 구조 분해 문법 미적용 코드는 이렇게 해야 아래와 위상이 맞을 것 같아요 😄

2021-09-01 22:52 UTC, merged