Todo app example
joshua1988/vue-camp pull request #76
Opened 2021-08-23 17:03 UTC by dngwoodo

## 관련 이슈

# 33

## 요약

`할 일 추가하기` 기능 구현과 테스트 코드 작성 파트 입니다.

2021-08-24 07:57 UTC, dngwoodo reviewed
셀프 리뷰 및 피드백이 필요한 부분들을 적어봤습니다 :)

2021-08-24 07:57 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +    // wrapper.find("input").trigger("input");
이 부분은 조금 헷갈리는 데 이벤트 트리거는 공식문서에서 비동기로 취급하는 것 같습니다. 근데 테스트 해보니 input 이벤트 트리거는 동기적으로 동작하는 것 같습니다. 

https://vue-test-utils.vuejs.org/api/wrapper/setvalue.html

2021-08-24 07:57 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +그리고 위의 테스트 코드에서 `describe`, `it`의 첫 번째 인수를 합쳐보면 `App renders label, input`, `App renders button`으로 문장이 만들어지는 것을 보실 수 있습니다. `render`는 `App`이 단수이기 때문에 뒤에 s를 붙여서 `renders`로 작성하는 겁니다. 이런 식으로 문법에 맞게 작성해주세
이 부분 밑에 테스트 코드 실행 시 터미널 창에 출력되는 문장들의 이미지를 넣어줘도 좋을 것 같습니다.

2021-08-24 07:57 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +
package.json에  `"test:unit": "vue-cli-service test:unit"`을 `"test:unit": "vue-cli-service test:unit --watchAll"`로 변경하는 내용이 있으면 좋을 것 같습니다. 테스트를 작성하고 수정할 때 마다 실행시키면 불편할 것 같네요.

2021-08-24 07:57 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +import { shallowMount } from "@vue/test-utils";
굳이 shallowMount를 써야 되나 고민입니다. 저는 테스트를 작성할 때 사용자에게 보여지는 것에 초점을 두고 테스트 코드를 작성하는 데 공통적인 컴포넌트는 따로 컴포넌트로 만들어서 사용하는 경우가 많다고 생각되서 shallowMount를 쓰면 그게 조금 어려울 것 같습니다.

2021-08-24 12:39 UTC, yahma25 reviewed
진행이 빠르시네요~ 🚀  피드백 남겼습니다~
vue는 아직 학습중이라 코드 내용면에선 아직 할 말이 많지않네요 😅

2021-08-24 12:39 UTC, yahma25 commented on docs/testing/tutorial-todo-app.md
> +`click`이벤트 트리거는 비동기로 동작하기 때문에 `async, await`문법을 사용하여 동기적으로로 동작하게 만듭니다. `control` 창에 할 일을 타이핑하고 `추가하기 button`이 클릭 됐을 때 타이핑한 할 일이 화면에 출력 되는지 테스트합니다.
```suggestion
`click`이벤트 트리거는 비동기로 동작하기 때문에 `async, await`문법을 사용하여 동기적으로로 동작하게 만듭니다. `control` 창에 할 일을 타이핑하고 `추가하기` 버튼이 클릭 됐을 때 타이핑한 할 일이 화면에 출력 되는지 테스트합니다.
```
[제안]
글 윗 부분에서 `추가하기` 버튼 식으로 표현을 해와서 동일하게 맞춰주면 좋을 것 같아요 😄

2021-08-29 09:09 UTC, amorfati0310 reviewed
안녕하세요 동우님 수고많으셨습니다. 점차 주가되는  todo예제들이 기대가 되네요

2021-08-29 09:09 UTC, amorfati0310 commented on docs/testing/tutorial-todo-app.md
> +    // wrapper.find("input").trigger("input");
문서랑 직접 비교하기 어려운게 mount, shallowMount 그리고 문서에서는 await 한 후 input element에 value랑 비교하고 있어서 api 비교를 다시 한 번 해보셔야 할 것 같아요. 문서처럼 이벤트 후에 dom 변화를 다시 테스트 코드로 살펴보려면 await가 필요해보이네요

2021-08-29 09:09 UTC, amorfati0310 commented on docs/testing/tutorial-todo-app.md
> +        <button type="button" @click="handleClick">추가하기</button>
테스트 내용이랑은 크게 상관없지만 코딩 스타일 적으로 피드백 드려요 
- addTodo ui 이벤트에 맞춘 이름 보다 어떤 행위인지 명시적인 메소드 명이면 더 좋을 것 같습니다 
- form으로 쓰기 때문에 버튼 type=submit으로 받아서 enter 이벤트도 쉽게 받을 수 있도록 처리해서 form에서 submit이벤트로 받아서 할 일 을 추가해주면 더 좋을 것 같네요

2021-08-29 09:09 UTC, amorfati0310 commented on docs/testing/tutorial-todo-app.md
> +  wrapper.find("input").setValue("아무것도 안하기");
line을 
given 
when 
then 
에 맞춰서 
setValue랑 awiat단락은 묶어주면 더 좋을 것 같습니다

2021-08-29 09:09 UTC, amorfati0310 commented on docs/testing/tutorial-todo-app.md
> +it("listens click event", async () => {
여기도 클릭이벤트 테스트 라는 description 보다는 
할일 추가 테스트 |  할 일 작성 후 리스트에 제대로 값이 있는지 테스트  등 조금 더 명시적으로 적어주시면 좋을 것 같습니다

2021-08-29 09:22 UTC, amorfati0310 commented on docs/testing/tutorial-todo-app.md
> +import { shallowMount } from "@vue/test-utils";
child component가 따로 없는 지금 같은 상황에서는 비용적인 측면에서 유리한 면이 있기 때문에 shallowMount 잘 쓰신 것 같네요 
고민하신 것 처럼 여러 컴포넌트의 동작에 확인이 필요할 때는 mount를 주로 쓸 것 같네요

2021-08-30 00:33 UTC, jm-chong commented on docs/testing/tutorial-todo-app.md
> +  wrapper.find("input").setValue("아무것도 안하기");
given/when/then 좋습니다.

2021-08-30 11:49 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +describe("App", () => {
피드백 감사합니다 :) 저는 테스트 코드를 작성할 때 `describe - context -it` 구조로 작성을 하고 있는데요. 예를 들어 밑에처럼 
```js
describe('App', () => {
   context('when logged in', () => {
     it('renders profile', () => {})
  })
})
```

`App when logged in renders profile`  이런식으로 문장이 이어지게 작성하고 있습니다. 이렇게 작성하는 것에 대해서는 어떻게 생각하실까요 ?

2021-08-30 11:50 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +1. 기능 구현 - `control`창에 할 일 작성 시 data에 할 일 텍스트 값 넣기
피드백 감사합니다 :) 말씀하신대로 수정해보겠습니다!

2021-08-30 12:13 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +  it("listens input event", () => {
피드백 감사합니다:) 이 테스트 코드 의도 자체가 input event 발생에 대한 테스트입니다. 
```js
it('listens input event when change input value', () => {})
```
이런식으로 적어주는 것에 대해서 멘토님은 어떻게 생각하시나요 ?

2021-08-30 12:14 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +        <button type="button" @click="handleClick">추가하기</button>
피드백 감사합니다 :) 말씀해주신대로 변경해보겠습니다!

2021-08-30 12:19 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +  wrapper.find("input").setValue("아무것도 안하기");
피드백 감사합니다 :) 패턴에 맞춰서 변경해보겠습니다!

2021-08-30 12:23 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +it("listens click event", async () => {
피드백 감사합니다 :) 이 부분도 https://github.com/joshua1988/vue-camp/pull/76#discussion_r698434178 마찬가지로 테스트 의도가 click event가 발생되는 것에 두고 있어서
```js
it('listens click event when click '추가하기' button', () => {})
```
로 작성하는 해보려고 합니다. 멘토님 의견은 어떠실까요 ?

2021-08-30 12:24 UTC, amorfati0310 commented on docs/testing/tutorial-todo-app.md
> +  it("listens input event", () => {
테스트코드에 의도 자체가 이벤트 리슨이면 의도하신대로 적는게 맞는 것 같아요. 
input events listen을 test하는거면 함수 콜만 비교해도 될 것 같네요 ,
뒤에 비교하는 부분 vm.text랑 값을 비교하는 부분이 있어서  그 부분이랑 매칭이 되면 더 좋을 것 같아요

2021-08-30 12:25 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +    // wrapper.find("input").trigger("input");
피드백 감사합니다:) 한번 더 확인해보고 변경하도록 하겠습니다!

2021-08-30 12:26 UTC, amorfati0310 commented on docs/testing/tutorial-todo-app.md
> +describe("App", () => {
얘기하신 `describe - context -it` 룰에 맞춰서 작성하시는 것도 좋아 보입니다 👍

2021-08-30 12:31 UTC, yahma25 commented on docs/testing/tutorial-todo-app.md
> +describe("App", () => {
저도 다른 분들은 어떻게 하고 계신지 궁금하네요. 🙄 
회사에서는, 한글로 작성하고 있는데 `describe`에는 제목을, 테스트 로직이 있는 `it 대신 test`에는 검증할 내용을 작성하고 있어요.

2021-08-30 12:42 UTC, amorfati0310 commented on docs/testing/tutorial-todo-app.md
> +it("listens click event", async () => {
어 이 부분도 테스트 스펙이랑 확인하는 과정을 보면 할 일을 추가 버튼을 누르고 할일이 추가된 것을 확인하는 테스트 같은데 어떻게 생각하시나요?

2021-08-30 12:48 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +describe("App", () => {
한글을 쓴다면 저도 describe에 테스트하는 컴포넌트 이름을 적고 it보단 test를 사용해서 검증할 내용을 작성할 것 같습니다. 명호님이 사용하고 계시는 테스트 코드의 예시를 하나 들어주실 수 있을까요 ? 😊

2021-08-30 13:24 UTC, yahma25 commented on docs/testing/tutorial-todo-app.md
> +describe("App", () => {
```js
describe('요소 기능 제한 테스트', () => {
  // ...
  describe('체크 기능 테스트', () => {
    test('허용 리스트에 존재하면 제한된 것으로 간주한다', () => {
      // ...
    });
    test('리스트에 존재하지 않으면 제한되지 않은 것으로 간주한다', () => {
      // ...
    });
  });
});
```

Webstorm 기준 IDE에서 결과를 볼 때 아래와 같이 나와요.
```
▼ √ Test Results
  ▼ √ xxx_test.ts
    ▼ √ 요소 기능 제한 테스트
      ▼ √ 체크 기능 테스트
            √ 허용 리스트에 존재하면 제한된 것으로 간주한다
            √ 리스트에 존재하지 않으면 제한되지 않은 것으로 간주한다
```

컨벤션에 따른 차이일 것 같아요. 😄 (저흰 테스트 코드에 대한 컨벤션은 없고 1세대 개발자들을 따라서 작성을...ㅋ)

Vue.js github에서는 테스트 영역마다 다르기도 하네요. 🤔 
ex 1) [ssr-string.spec.js](https://github.com/vuejs/vue/blob/dev/test/ssr/ssr-string.spec.js)
ex 2) [show.spec.js](https://github.com/vuejs/vue/blob/dev/test/unit/features/directives/show.spec.js)

개인적으론 동우님이 작성하시는 스타일로 해보는 것도 좋을 것 같아요 👍

2021-08-30 13:53 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +그리고 위의 테스트 코드에서 `describe`, `it`의 첫 번째 인수를 합쳐보면 `App renders label, input`, `App renders button`으로 문장이 만들어지는 것을 보실 수 있습니다. `render`는 `App`이 단수이기 때문에 뒤에 s를 붙여서 `renders`로 작성하는 겁니다. 이런 식으로 문법에 맞게 작성해주세
https://github.com/joshua1988/vue-camp/pull/76/commits/bba60dfc26089b565b3b5153f9f5c2debc71de01 에서 추가했습니다.

2021-08-30 13:53 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +[완성 코드]()
https://github.com/joshua1988/vue-camp/pull/76/commits/f671d43dd331a9ab3817ff9337a69d8449f8cf3d 에서 추가했습니다.

2021-08-30 13:54 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +    // wrapper.find("input").trigger("input");
https://github.com/joshua1988/vue-camp/pull/76/commits/cf4eab52d1ed247901075d78374d7cfff12e5323 에서 변경했습니다 :)

2021-08-30 13:55 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +it("listens click event", async () => {
생각해보니 클릭 이벤트를 테스트 하는 것 보단 기능 구현과 일치시키는 게 맞다고 생각 됩니다.
https://github.com/joshua1988/vue-camp/pull/76/commits/29881604cba1344ee67297881859278a2afa2e73 에서 테스트 검증문을 수정했습니다 :)

2021-08-30 13:56 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +  it("listens input event", () => {
https://github.com/joshua1988/vue-camp/pull/76#discussion_r698509989

2021-08-30 13:56 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +  wrapper.find("input").setValue("아무것도 안하기");
https://github.com/joshua1988/vue-camp/pull/76/commits/5c4ab79217990fc306d6e1ccb9753875773a6b36 에서 변경했습니다 :)

2021-08-30 13:57 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +        <button type="button" @click="handleClick">추가하기</button>
한번 더 생각해보니 `form` 태그를 굳이 써야 되나 라는 생각을 가지게 되어 https://github.com/joshua1988/vue-camp/pull/76/commits/54b873552a77f6c419010224ada9c60a075e15c0 에서 `form` -> `div`로 변경해주는 작업을 했습니다.

2021-08-30 13:59 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +- 할 일을 작성할 수 있는 `control`이 화면에 출력됩니다.
https://github.com/joshua1988/vue-camp/pull/76/commits/5f423c8868dd79b718ecf6fc97e0c60d83d4cd5c 에서 `control창`을  `input창`으로 변경해주었습니다 :)

2021-08-30 14:00 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +1. 기능 구현 - `control`창에 할 일 작성 시 data에 할 일 텍스트 값 넣기
https://github.com/joshua1988/vue-camp/pull/76#discussion_r698513406

2021-08-30 14:10 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +describe("App", () => {
테스트 코드 작성에 정답은 없는 것 같습니다 ㅎㅎ 개인적인 생각으론 다른 사용자들이 보기에 해당 테스트의 의도가 가독성 있게 잘 읽힌다면 상관 없을 것 같습니다. 혹시나 jest에서 context를 사용하시게 된다면  jest-plugin-context 라이브러리를 사용해보시면 좋을 것 같습니다. context에는 when, with를 사용해서 작성하며 테스트 검증문의 길이를 줄여주고 가독성을 높여줍니다.

https://www.betterspecs.org/#contexts

2021-08-30 14:34 UTC, yahma25 commented on docs/testing/tutorial-todo-app.md
> +describe("App", () => {
처음 알게되네요. 공유 고마워요! 🚀

2021-09-01 15:24 UTC, joshua1988 requested changes
@dngwoodo 에고 동우님 제가 너무 늦게 피드백을 드렸죠.. 벌써 튜토리얼 진도가 많이 나갔네요. 상세하고 친절하게 잘 작성된 것 같습니다 😄 몇 가지 피드백 남겼는데 보시고 의견 있으시면 남겨주세요! :)

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +[완성 코드](https://github.com/dngwoodo/vue-todo-app-test/tree/ec674be494e8c27f6440e689ab40714ec255c19e)
@dngwoodo 동우님 요 부분은 지난번 PR에서 말씀 드렸어야 했는데 요건 단어 하나만 툭 튀어나오는 것 보다 좀 더 설명이 들어가면 좋을 것 같아요 😄 

할 일 추가하기의 구현 순서는 다음과 같으며 최종 코드는 [여기서]() 확인하실 수 있습니다.

대략 이런 식으로..? 😄

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +- 할 일을 작성할 수 있는 `input 창`이 화면에 출력됩니다.
```suggestion
- 할 일을 작성할 수 있는 인풋 태그가 화면에 출력됩니다.
```

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +- `할 일 작성`이라는 텍스트가 화면에 출력됩니다.
```suggestion
- "할 일 작성"이라는 텍스트가 화면에 출력됩니다.
```

그 저희가 백틱은 인라인 코드에만 적용하는게 좋을 것 같아서 별도의 강조 표시가 필요하시다면 큰 따옴표나 * 쓰면 좋을 것 같습니다 😄

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +한가지 알아두셔야 할 것은 테스트 코드는 작성하는 사람에 따라 얼마든지 달라질 수 있습니다. 테스트 코드를 얼마나 세세하게 작성하냐에 따라서 코드의 안전성이 달라집니다. 즉, 테스트 코드를 작성한다고 해서 모든 에러를 방지할 수 있는 게 아닙니다. 그러므로 학습하실 때는 조금이라도 더 세세하게 테스트를 작성해보시는 걸 권장해 드립니다.
문서 전반적으로 맞춤법 검사를 한번 하면 좋을 것 같아요! 😄

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +describe("App", () => {
저도 여기에 제 의견을 좀 공유해 드리고 싶은데요..! 이미 다들 잘 애기 나눠 주셔서 넘 늦게 온거 같기도 한데.. ㅎㅎ

1. 일단 저도 동우님처럼 describe, it 단위로 작성하는게 편한 것 같습니다. 테스트 파일을 쪼개기 나름인 것 같아요.
2. 그리고 보다 보니까 저는 보통 expect 안에 여러 개의 API를 연결해서 바로 넣는 것보다는 아래와 같은 형태로 작성하는데요. 이게 좀 더 어떤 걸 테스트 하는 건지 눈에 잘 들어오는 것 같아요. 뭐 이런건 취향 차이일수 있으니까 ㅋㅋ

```js
it("renders title", () => {
    const wrapper = shallowMount(App);
    const headingText = wrapper.find("h1").text();
    expect(headingText).toMatch("Todo App");
  });
```

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +막상 테스트 코드를 작성을 하고 보니 한가지 아쉬운 게 있습니다. `input 창`과 `label`이 연결된 지도 확인해보고 싶습니다. 테스트를 하나 더 추가해보겠습니다.
```suggestion
막상 테스트 코드를 작성을 하고 보니 한 가지 아쉬운 게 있습니다. 인풋 태그와 레이블이 연결됐는지도 확인해보고 싶습니다. 테스트를 하나 더 추가해보겠습니다.
```

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +그리고 위의 테스트 코드에서 `describe`, `it`의 첫 번째 인수를 합쳐보면 `App renders label, input`, `App renders button`으로 문장이 만들어지는 것을 보실 수 있습니다. `render`는 `App`이 단수이기 때문에 뒤에 s를 붙여서 `renders`로 작성하는 겁니다. 이런 식으로 문법에 맞게 작성해주세
@dngwoodo 엇 여기 인수가 무슨 의미인가요? 인자인가요?

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +그리고 위의 테스트 코드에서 `describe`, `it`의 첫 번째 인수를 합쳐보면 `App renders label, input`, `App renders button`으로 문장이 만들어지는 것을 보실 수 있습니다. `render`는 `App`이 단수이기 때문에 뒤에 s를 붙여서 `renders`로 작성하는 겁니다. 이런 식으로 문법에 맞게 작성해주세
@dngwoodo 오 여기 테스트 코드는 말이 되게 작성해라 라고 하는 포인트 넘 좋네요 😄

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +1. 기능 구현 - `input 창`에 할 일 작성 시 data에 할 일 텍스트 값 넣기
@dngwoodo 요거 인풋 창도 정리해주세요 😄

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +v-model을 사용하지 않은 이유는 현재 시점에서는 IME 입력(한국어, 일본어, 중국어)에 대해서 한계점이 있기 때문입니다. 자세한 내용은 이 [링크](https://joshua1988.github.io/web-development/vuejs/v-model-usage/#%EA%B7%B8%EB%9F%BC-v-model%EC%9D%B4-%EB%8D%94-
@dngwoodo 그쵸 테스트 코드 볼 정도면 이제 실무하시는 분들이니까 v-model이 아니라 `:value @input` 조합 넘 좋습니다 😄

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +1. 기능 구현 - `input 창`에 할 일 작성 시 data에 할 일 텍스트 값 넣기
```suggestion
3. 기능 구현 - `input 창`에 할 일 작성 시 data에 할 일 텍스트 값 넣기
```

요게 3번 맞죠?

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +vue-test-utils 라이브러리에선 `input`이벤트를 `trigger`시 `event.target.value`를 직접적으로 변경할 수 없습니다. 그래서 `input`의 `value`값을 변경한 뒤 `input`이벤트를 `trigger`해야 합니다. `input`이벤트를 `trigger`하면 `handleInput`함수가 실행되고 `data`의 `
```suggestion
vue-test-utils 라이브러리에선 `input`이벤트를 `trigger`시 `event.target.value`를 직접적으로 변경할 수 없습니다. 그래서 `input`의 `value`값을 변경한 뒤 `input`이벤트를 `trigger`해야 합니다. `input`이벤트를 `trigger`하면 `handleInput`함수가 실행되고 `data`의 `text`값이 변경됐는지 테스트합니다. 그리고 이벤트 트리거는 비동기로 동작하기 때문에 `async, await`문법을 사용하여 실행 순서를 보장해 주어야 합니다.
```

요렇게 풀어서 써보는 건 어떨까요? 😄

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +        <!-- @click="handleClickAddTodo" 추가 -->
@dngwoodo 뷰 프레스에서 추가된 영역을 강조하는 문법이 있는데요. 이거 다른 문서들 참고하셔서 주석들 제거하고 추가된 곳들을 강조해 보면 어떨까요? 😄

2021-09-01 15:24 UTC, joshua1988 commented on docs/testing/tutorial-todo-app.md
> +`input 창`에 할 일을 타이핑하고 `추가하기` 버튼이 클릭 됐을 때 타이핑한 할 일이 화면에 출력 되는지 테스트합니다.
@dngwoodo 요것도 정리 부탁드려요 😄

2021-09-02 04:44 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +[완성 코드](https://github.com/dngwoodo/vue-todo-app-test/tree/ec674be494e8c27f6440e689ab40714ec255c19e)
피드백 감사합니다 :) https://github.com/joshua1988/vue-camp/pull/76/commits/baf2578fe53ce5fe1c65be42f7ce1716c839d5f7 에서 변경했습니다.

2021-09-02 04:47 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +- 할 일을 작성할 수 있는 `input 창`이 화면에 출력됩니다.
피드백 감사합니다:) https://github.com/joshua1988/vue-camp/pull/76/commits/10bfb4859f4c7182e6d97effaefc7d51414acc75 에서 수정했습니다. 커밋을 나눌필요가 있어보이는데 실수로 두가지 수정을 한 커밋에 넣어버렸네요..🥲

2021-09-02 04:48 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +한가지 알아두셔야 할 것은 테스트 코드는 작성하는 사람에 따라 얼마든지 달라질 수 있습니다. 테스트 코드를 얼마나 세세하게 작성하냐에 따라서 코드의 안전성이 달라집니다. 즉, 테스트 코드를 작성한다고 해서 모든 에러를 방지할 수 있는 게 아닙니다. 그러므로 학습하실 때는 조금이라도 더 세세하게 테스트를 작성해보시는 걸 권장해 드립니다.
피드백 감사합니다:) https://github.com/joshua1988/vue-camp/pull/76/commits/10bfb4859f4c7182e6d97effaefc7d51414acc75 에서 수정했습니다. 

한가지 -> 한 가지 로 수정

2021-09-02 04:48 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +막상 테스트 코드를 작성을 하고 보니 한가지 아쉬운 게 있습니다. `input 창`과 `label`이 연결된 지도 확인해보고 싶습니다. 테스트를 하나 더 추가해보겠습니다.
피드백 감사합니다 :) https://github.com/joshua1988/vue-camp/pull/76/commits/10bfb4859f4c7182e6d97effaefc7d51414acc75 에서 수정했습니다.

2021-09-02 04:49 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +1. 기능 구현 - `input 창`에 할 일 작성 시 data에 할 일 텍스트 값 넣기
실수했네요 ㅎㅎ.. 피드백 감사합니다 :) https://github.com/joshua1988/vue-camp/pull/76/commits/9ddb2c395b66ed20435b6bb5a2a45f1cc3e00265 에서 수정했습니다.

2021-09-02 04:50 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +vue-test-utils 라이브러리에선 `input`이벤트를 `trigger`시 `event.target.value`를 직접적으로 변경할 수 없습니다. 그래서 `input`의 `value`값을 변경한 뒤 `input`이벤트를 `trigger`해야 합니다. `input`이벤트를 `trigger`하면 `handleInput`함수가 실행되고 `data`의 `
피드백 감사합니다 :) 비동기라는 단어의 반댓말만 생각하고 풀어서 설명할 생각은 안해봤었네요 🥲  https://github.com/joshua1988/vue-camp/pull/76/commits/fc6f1fac3dc3f85fd51dc77e218c9ad7658d1289 에서 수정했습니다.

2021-09-02 04:50 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +`input 창`에 할 일을 타이핑하고 `추가하기` 버튼이 클릭 됐을 때 타이핑한 할 일이 화면에 출력 되는지 테스트합니다.
피드백 감사합니다:) https://github.com/joshua1988/vue-camp/pull/76/commits/10bfb4859f4c7182e6d97effaefc7d51414acc75 여기서 일괄 수정 했습니다.

2021-09-05 04:30 UTC, dngwoodo commented on docs/testing/tutorial-todo-app.md
> +        <!-- @click="handleClickAddTodo" 추가 -->
피드백 감사합니다 :) https://github.com/joshua1988/vue-camp/pull/76/commits/a6ad272fda33926592a149030e5cc902bab7a518 에서 수정했습니다.

2021-09-05 06:13 UTC, amorfati0310 reviewed
안녕하세요 동우님 한 번 더 살펴보시고 merge 하셔도 좋을 것 같아요 👍

2021-09-05 06:13 UTC, amorfati0310 commented on docs/testing/tutorial-todo-app.md
> +- `할 일 작성`이라는 텍스트가 화면에 출력됩니다.
@dngwoodo 님 안녕하세요 이쪽 백틱쪽만 한 번 ""로 고치는게 좋은 부분 있는지 보면 좋을 것 같네요

2021-09-05 14:05 UTC, dngwoodo commented
> 안녕하세요 동우님 한 번 더 살펴보시고 merge 하셔도 좋을 것 같아요 👍

놓쳤었네요 ㅎㅎ https://github.com/joshua1988/vue-camp/pull/76/commits/4303d6eb19614ca22392e13d5acc977f011fb3cb 에서 수정했습니다.

2021-09-06 14:52 UTC, merged