[doc] 화살표함수 this 문서화
joshua1988/vue-camp pull request #92
Opened 2021-08-27 04:02 UTC by Kyounghwan01

## 관련 이슈

#42 

## 요약

화살표 함수에 this 부분 추가하였습니다. 리뷰 부탁드리겠습니다!

2021-08-29 10:01 UTC, jm-chong commented on docs/es6/fat-arrow.md
> +그래서 addEventListener 함수에서 this를 사용하는 경우, 화살표 함수가 아닌 일반 함수를 사용합니다. 일반 함수로 정의된 addEventListener 함수의 this는 currentTarget을 가리킵니다.
명호님 의견처럼, event객체를 가리키는 의미로, `this`를 사용하기도 하지만, 
```
button.addEventListener('click', function(e) {
    const elTarget = e.currentTarget;
});
```

과 같이, 이벤트 객체를 함수 파라메터로 받아서 표현하기도 합니다.
이렇게 할 경우 `this`에 대한 혼돈을 조금 줄일 수 있을것 같습니다.

2021-08-29 10:10 UTC, amorfati0310 requested changes
경환님 수고 많으셨습니다~~. 몇 가지 다듬으면 좋을 만한 부분에 피드백 드렸어요 한 번 살펴보시고 수정해보시면 좋을 것 같아요

2021-08-29 10:10 UTC, amorfati0310 commented on docs/es6/fat-arrow.md
> +addEventListener 두 번째 인자로 화살표 함수를 넣으면 this는 상위 스코프의 this를 가리킵니다.
## this 바인딩 개념에 맞춘 예시여서 
### setTimeout에서의 this
### addEventListener에서의 this 가 
바로 같이 나와도 될 것 같고요 + h3 단락없이 바로 예시로 적어줘도 좋을 것 같네요.

2021-08-29 10:10 UTC, amorfati0310 commented on docs/es6/fat-arrow.md
> +class 내부에서 addEventListener 콜백 함수로 사용되는 this는 선언된 class로 값이 바인딩 됩니다. 아래 예시 코드를 참조해주시기 바랍니다.
this가 class가 아니라 클래스로 생성된 객체에 binding 되지 않을까요?

2021-08-30 12:23 UTC, Kyounghwan01 commented
피드백 반영하였습니다!

2021-09-04 16:48 UTC, daep93 commented on docs/es6/fat-arrow.md
> +    console.log(this); // {name: "bar", age: 10000, getAge: ƒ}
경환님, 결과값이 잘못 적힌 것 같습니다. ``` {name: "bar", age: 10000, printThis: ƒ} ```로 바뀌어야할 것 같습니다.

2021-09-04 17:02 UTC, daep93 reviewed
@Kyounghwan01 안녕하세요, 경환님!
경환님 덕분에 this에 대해서 모르는 부분을 더 공부할 수 있었습니다. 감사합니다 😄 
제가 몇 가지 코멘트 남겼는데 코멘트 남기는 방법에 미숙해서 일관성있게 적질 못한 것 같습니다. 양해 부탁드릴게요🥲

2021-09-05 06:35 UTC, amorfati0310 approved these changes
수고많으셨습니다

2021-09-05 09:16 UTC, Kyounghwan01 commented
> @Kyounghwan01 안녕하세요, 경환님!
> 경환님 덕분에 this에 대해서 모르는 부분을 더 공부할 수 있었습니다. 감사합니다 😄
> 제가 몇 가지 코멘트 남겼는데 코멘트 남기는 방법에 미숙해서 일관성있게 적질 못한 것 같습니다. 양해 부탁드릴게요🥲

@daep93   수정하였습니다 감사합니다~!

2021-09-07 13:00 UTC, Kyounghwan01 commented
@jm-chong @joshua1988 pr 부탁드리겠습니다!

2021-09-08 00:00 UTC, jm-chong approved these changes
수고하셨습니다. 👍 
this는 볼때마다 헷갈리네요 ㅎㅎ

2021-09-08 00:00 UTC, jm-chong commented on docs/es6/fat-arrow.md
> +    innerFunc = () => {
innerFunc는 printThis안의 지역변수인가요? 그렇다면 const나 let(혹은 var?)로 선언해주는게 좋을것 같네요

2021-09-08 00:00 UTC, jm-chong commented on docs/es6/fat-arrow.md
> +      console.log(this); // {name: "bar", age: 10000, getAge: ƒ}
여기도 `getAge`함수가 찍히면 안될거 같습니다. 전체적인 확인 부탁드려요

2021-09-08 00:00 UTC, jm-chong commented on docs/es6/fat-arrow.md
> +addEventListener 두 번째 인자로 화살표 함수를 넣으면 this는 상위 스코프의 this를 가리킵니다.
`addEventListener의 이벤트 콜백함수` 로 용어가 변경되면 좀 더 명확할 것 같습니다.

2021-09-08 00:00 UTC, jm-chong commented on docs/es6/fat-arrow.md
> +class 내부에서 addEventListener 콜백 함수로 사용되는 this는 선언된 class로 생성된 객체의 값이 바인딩 됩니다. 아래 예시 코드를 참조해주시기 바랍니다.
아래처럼 수정해보면 어떨까요?
`addEventListener 콜백 함수 안에서 사용되는 this는 class로 생성된 객체 인스턴스를 가리킵니다`

2021-09-08 00:00 UTC, jm-chong commented on docs/es6/fat-arrow.md
> +    console.log(e.keyCode); // e를 누르면 63
영문 `e` 키를 의미하는거 같은데, e 변수와 의미가 혼동되는거 같습니다.
`Entry Key`를 누르면 13 정도는 어떠실까요?

2021-09-08 12:13 UTC, Kyounghwan01 commented on docs/es6/fat-arrow.md
> +    console.log(e.keyCode); // e를 누르면 63
넵 수정하였습니다!

2021-09-08 12:13 UTC, Kyounghwan01 commented on docs/es6/fat-arrow.md
> +class 내부에서 addEventListener 콜백 함수로 사용되는 this는 선언된 class로 생성된 객체의 값이 바인딩 됩니다. 아래 예시 코드를 참조해주시기 바랍니다.
수정하였습니다.

2021-09-08 12:14 UTC, Kyounghwan01 commented on docs/es6/fat-arrow.md
> +      console.log(this); // {name: "bar", age: 10000, getAge: ƒ}
수정하였습니다

2021-09-08 12:14 UTC, Kyounghwan01 commented on docs/es6/fat-arrow.md
> +    innerFunc = () => {
수정하였습니다

2021-09-08 12:15 UTC, merged