[doc] javascript collection 가이드 문서 작성
joshua1988/vue-camp pull request #93
Opened 2021-08-27 13:06 UTC by ChoiSangok

Signed-off-by: ChoiSangOk <tkddhr12345@naver.com>

## 관련 이슈

#72 

## 요약

javascript collection 중 map, set 가이드 문서화를 진행했습니다.

피드백 부탁드립니다..!

## 리뷰어

2021-08-28 09:19 UTC, ChoiSangok commented on docs/js/collection.md
> +set.add("javascript").add("vue").add("node");
넵 이부분은 2가지 방법? 으로 의도해서 나타낸겁니다. 많은 수정사항 알려주셔서 감사합니다~!

2021-08-29 10:33 UTC, jm-chong requested changes
Map과 Set에 대한 설명이군요. 유익하네요.

몇가지 수정 코멘트를 드렸고

전체적인 내용의 흐름을 아래처럼 가져가면 더 좋을것 같습니다

- 객체의 생성
  - 빈 객체를 생성하는 방법
  - 초기 데이터를 넣어서 객체를 생성하는 방법
- 객체의 데이터를 추가/삭제하는 방법
- 객체를 순회하는 방법
  - forEach이외에, values, keys, entries등으로 순회하는 방법.
- 이외 주요 메서드와 프로퍼티

2021-08-29 10:33 UTC, jm-chong commented on docs/js/collection.md
> +- `map.get(key, value)`: key 에 해당하는 값을 반환합니다.
`get`을 설명하시는거라면, 두번째 `value` 파라미터는 없어야 할것 같습니다.

2021-08-29 10:33 UTC, jm-chong commented on docs/js/collection.md
> +- `map.hash(key)`: key가 존재하면 true, 존재하지 않으면 false를 반환합니다.
`has`를 의미하시는것 같습니다.

2021-08-29 10:33 UTC, jm-chong commented on docs/js/collection.md
> +set.add("javascript").add("vue").add("node");
method Channing 이 된다는것을 보여주시려는거 같네요

2021-08-29 10:33 UTC, jm-chong commented on docs/js/collection.md
> +- `map.size()`: 요소의 개수를 반환합니다.
Map객체의 `size`는 method가 아니라 `property`입니다.

2021-08-29 10:33 UTC, jm-chong commented on docs/js/collection.md
> +- `set.size`: 세트의 크기를 반환합니다.
이것도 property이기 때문에 '반환한다'는 표현보다는, Set의 크기를 나타냅니다.. 정도로 표현이 바뀌면 좋겠습니다.

2021-09-05 07:04 UTC, amorfati0310 requested changes
안녕하세요 상옥님 수고 많으셨습니다.

2021-09-07 00:38 UTC, daep93 commented
안녕하세요, 상옥님. 멘티 박대현입니다. config.js에 collection 페이지 등록이 빠져있던데 등록 후에 push 해주실 수 있을까요?

2021-09-07 01:45 UTC, ChoiSangok commented on docs/js/collection.md
> +- `map.get(key, value)`: key 에 해당하는 값을 반환합니다.
넵ㅠㅠ! 저번주에 확인을 못해서, 수정사항 반영 했습니다! 감사합니다.

2021-09-07 01:52 UTC, ChoiSangok commented
> 안녕하세요, 상옥님. 멘티 박대현입니다. config.js에 collection 페이지 등록이 빠져있던데 등록 후에 push 해주실 수 있을까요?

아넵! 같이 push 했습니다. 알려주셔서 감사합니다!

2021-09-08 12:23 UTC, joshua1988 requested changes
@ChoiSangok 상옥님 글 읽기 편하고 좋네요. 고생 많으셨습니다 😄 👍 👍 피드백 몇 개 남긴거 확인하시고 수정되면 머지 하시면 될 것 같아요 😄

2021-09-08 12:23 UTC, joshua1988 commented on docs/js/collection.md
> +const map = new Map([['key1', 'value1'], ['key1','value2']]);
```suggestion
const map = new Map([['key1', 'value1'], ['key1',' value2']]);
```

2021-09-08 12:23 UTC, joshua1988 commented on docs/js/collection.md
> +// 결과입니다.
```suggestion
// 결과입니다
```

2021-09-08 12:23 UTC, joshua1988 commented on docs/js/collection.md
> +for(let key of map.keys()){
보통 `for (let key of ..` 이런 형태로 인덴팅 주는 것 같아요 😄 아래도 같이 반영해주시면 좋을 것 같습니다 😄

2021-09-08 12:23 UTC, joshua1988 commented on docs/js/collection.md
> +set.add("node");
전반적으로 스트링에 작은 따옴표 쓰셨던데 여기도 통일해 주시면 좋을 것 같아요 😄

2021-09-13 03:52 UTC, ChoiSangok commented on docs/js/collection.md
> +set.add("node");
앗 넵! 피드백 주신거 수정했습니다! 감사합니다!

2021-10-10 12:41 UTC, merged