[doc] v-slot 가이드 문서 작성
joshua1988/vue-camp pull request #96
Opened 2021-08-29 06:15 UTC by pozafly

## 관련 이슈

https://github.com/joshua1988/vue-camp/issues/67

## 요약

컴포넌트 설계 문서 작성 전에 Slot에 대해 먼저 정리해야할 필요가 있을 것 같아,
Vue 2.6 버전에서 새로 등장한 `v-slot` 디렉티브 사용법 가이드 문서화 진행했습니다 :)

피드백 부탁드립니다.

## 리뷰어

2021-08-29 10:51 UTC, jm-chong approved these changes
LGTM 👍 
수고하셨습니다.
몇가지 코멘트 드렸습니다.

slot은 Vue에 가장 매력적인 특징중에 하나이므로, 많은분들이 잘 사용하실 수 있으면 좋겠네요

2021-08-29 10:51 UTC, jm-chong commented on docs/reuse/v-slot.md
> +단, `#="slotProps"`구문은 불가능합니다. 특수 기호로 표현하고 싶다면, `#default="slotProps"`와 같이 슬롯 이름을 지정해 주어야 합니다.
오.. 이부분 궁금했는데 언급이 잘 되었네요! 
`v-slot`으로 쓰거나
`#default`로 써야겠군요.. 😄

2021-08-29 10:51 UTC, jm-chong commented on docs/reuse/v-slot.md
> +`<template>`태그를 낭비하지 않고 간편한 문법을 사용할 수 있습니다. 그리고 가독성이 좋아집니다.
낭비라는 표현보다는..
> `<template>` 태그를 사용하므로써 장황해지는 표현을 간략하게 할 수 있으며, 덕분에 가독성 또한 좋아집니다. 
로 바꿔보면 어떨까요?

2021-08-29 10:51 UTC, jm-chong commented on docs/reuse/v-slot.md
> +단, `#="slotProps"`구문은 불가능합니다. 특수 기호로 표현하고 싶다면, `#default="slotProps"`와 같이 슬롯 이름을 지정해 주어야 합니다.
https://kr.vuejs.org/v2/guide/components-slots.html

> 범위를 모호하게 만들기 때문에 디폴트 슬롯을 위한 축약 문법은 이름이 있는 슬롯들과 함께 쓸 수 없습니다.

위 문서의 이 부분도 함께 언급되면 좋겠습니다.

2021-08-29 13:16 UTC, pozafly commented on docs/reuse/v-slot.md
> +단, `#="slotProps"`구문은 불가능합니다. 특수 기호로 표현하고 싶다면, `#default="slotProps"`와 같이 슬롯 이름을 지정해 주어야 합니다.
범위에 대한 부분 해당 문서 찾아서 보강하겠습니다!

2021-08-29 13:17 UTC, pozafly commented on docs/reuse/v-slot.md
> +`<template>`태그를 낭비하지 않고 간편한 문법을 사용할 수 있습니다. 그리고 가독성이 좋아집니다.
표현을 고쳐보도록 하겠습니다!

2021-08-29 14:37 UTC, pozafly commented
코멘트 주신 부분 수정하여 push 했습니다!

2021-08-30 00:22 UTC, jm-chong commented
> 코멘트 주신 부분 수정하여 push 했습니다!

수고 많으셨습니다. 👍

2021-09-04 15:48 UTC, daep93 commented on docs/reuse/v-slot.md
> +    <slot :fooProp="fooProps"></slot>
fooProps 오타가 있네요. fooProps에서 fooProp으로 바꾸면 될 것 같습니다 😄

2021-09-04 15:57 UTC, daep93 commented on docs/reuse/v-slot.md
> +    <template slot-scope="fooProps">
fooProp을 받아오는 것을 표현하고 싶었다면 186번째 줄처럼 구조 분해하는 것은 어떨까요?
```html {4,6}
<template>
  <foo>
    <template slot-scope="{ fooProp }">
      <div>{{ fooProp }}</div>
    </template>
  </foo>
</template>

2021-09-04 16:06 UTC, daep93 commented on docs/reuse/v-slot.md
> +    <template slot-scope="fooProps">
아... 개념을 다 설명하고 팁을 알려주기 위해서 구조 분해를 따로 한게 아니군요.. 제가 의도를 잘못 이해했습니다.
그렇다면 이렇게 바꾸는것은 어떨까요?
```html
<template>
  <foo>
    <template slot-scope="fooProps">
      <div>{{ fooProps.fooProp }}</div>
    </template>
  </foo>
</template>
```

2021-09-04 16:11 UTC, daep93 commented on docs/reuse/v-slot.md
> +스콥드 슬롯의 변수에 ES6 문법인, [디스트럭처링(Destructuring)](/es6/destructuring.html) 표현도 가능합니다.
/es6/destructuring.html 에서 언급한 대로 Destructing을 구조 분해 문법으로 표기하는 것은 어떨까요?

2021-09-04 16:14 UTC, daep93 commented on docs/reuse/v-slot.md
> +스콥드 슬롯은 Vue 3.0 이하의 버전에서는 계속 사용할 수 있습니다. 단 Vue 3.0 이상 버전에서 삭제되었으므로 Vue 2.6 이상을 사용하고 있다면, `v-slot`디렉티브를 통해 슬롯을 사용하도록 권장합니다.
윗 버전에서는 삭제되었으니 스콥드 슬롯을 자제하고 디렉티브 사용을 권장하기 때문에 개인적으로는 tip대신 warning이 더 어울리지 않을까 생각합니다. 어떻게 생각하시나요?

2021-09-05 03:12 UTC, pozafly commented on docs/reuse/v-slot.md
> +    <slot :fooProp="fooProps"></slot>
앗 그렇군요.. 오타가 있었네요 ㅠㅠ

2021-09-05 03:15 UTC, pozafly commented on docs/reuse/v-slot.md
> +    <template slot-scope="fooProps">
이렇게 표현하게 되면 밑에서 스콥드 슬롯 단점을 설명한 아래와 같은 예제 코드도 바꿔야하는데 너무 길어지게 되고, 헷갈리게 될 것같아 위와 같이 표현해놓았습니다 :) 

```
<foo>
  <bar slot-scope="fooProps">
    <baz slot-scope="barProps">
      <div slot-scope="bazProps">
        {{ fooProp }} {{ barProp }} {{ bazProp }}
      </div>
    </baz>
  </bar>
</foo>
```

2021-09-05 03:16 UTC, pozafly commented on docs/reuse/v-slot.md
> +스콥드 슬롯의 변수에 ES6 문법인, [디스트럭처링(Destructuring)](/es6/destructuring.html) 표현도 가능합니다.
말씀하신대로 구조 분해 문법 표현이 좋을 것 같습니다 !

2021-09-05 03:19 UTC, pozafly commented on docs/reuse/v-slot.md
> +스콥드 슬롯은 Vue 3.0 이하의 버전에서는 계속 사용할 수 있습니다. 단 Vue 3.0 이상 버전에서 삭제되었으므로 Vue 2.6 이상을 사용하고 있다면, `v-slot`디렉티브를 통해 슬롯을 사용하도록 권장합니다.
의미를 다시 생각해보니, warning 이 더 어울릴 것 같아요!

2021-09-05 03:22 UTC, pozafly commented on docs/reuse/v-slot.md
> +    <slot :fooProp="fooProps"></slot>
아래 예제 코드에서도 fooProp 말고 fooProps 를 사용해서 fooProps로 바꾸는게 좋을 것 같아요 :) 예제 코드 자체를 오브젝트로 표현하도록 고쳐보겠습니다!

2021-09-05 07:45 UTC, amorfati0310 approved these changes
대현님 수고많으셨습니다.

2021-09-05 07:45 UTC, amorfati0310 commented on docs/.vuepress/config.js
> +};
EOF 챙겨주시면 좋을 것 같아요 👍

2021-09-05 07:45 UTC, amorfati0310 commented on docs/reuse/v-slot.md
> +  <template v-slot:[dynamicsSlotName]>
```suggestion
  <template v-slot:[dynamicSlotName]>
```

2021-09-05 08:54 UTC, pozafly commented on docs/.vuepress/config.js
> +};
EOF라 하면 끝 지점에 붙는 세미콜론을 말씀하시는 걸까요?

2021-09-05 08:57 UTC, daep93 commented on docs/.vuepress/config.js
> +};
@pozafly End of File의 약자로 js 파일 끝에는 공백 줄이 하나 들어가는 것이 권장됩니다.

2021-09-05 09:06 UTC, pozafly commented on docs/.vuepress/config.js
> +};
아! 그렇군요! 감사합니다 대현님!!! :)

2021-09-08 12:33 UTC, joshua1988 requested changes
@pozafly 선태님, 제가 PR 리뷰가 넘 늦어져서 죄송해요 ㅜㅜ 써주신 글 재밌게 잘 봤습니다 :) 문서 컨벤션 차원에서 몇 가지 피드백 드렸구요. 개인적으로는 컴포넌트 이름들은 가급적 `foo`, `bar` 보다는 좀 더 의미 있는 이름으로 [공식 스타일 가이드](https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential) 맞춰서 실제 고민했던 케이스를 담아보면 어떨까 해요. 요건 지금 반영하시기에는 변경해야 하는 내용이 많아서 부담 되실텐데 이건 이후부터 반영해 주셔도 됩니다. 선태님 편하신대로 해주세요 😄 
넘 잘 봤습니다 굿굿!! 👍 👍

2021-09-08 12:33 UTC, joshua1988 commented on docs/reuse/v-slot.md
> +여기서 눈여겨봐야 할 부분은 하위 컴포넌트인 `<foo>`태그의 props가 상위 컴포넌트의 `<div>`태그로 전달되었다는 점입니다.
```suggestion
여기서 눈여겨봐야 할 부분은 하위 컴포넌트인 `<foo>`태그의 프롭스 속성이 상위 컴포넌트의 `<div>`태그로 전달되었다는 점입니다. 
```

2021-09-11 02:36 UTC, pozafly commented
@joshua1988 기효님. 문장 수정 짚어주신 부분은 수정되었습니다! 짚어주신 `foo`, `bar` 부분은 실제 개발자가 사용하는 예시로 바꾸는게 좋다는 말씀이실까요? 여기서는 문법 위주로 설명하고, 지금 준비하고 있는 컴포넌트 설계 관련 문서에 실제적인 예시를 통해 설명하려고 했거든요..

2021-09-11 05:48 UTC, joshua1988 commented
@pozafly 오 네 선태님, 이건 제 개인적인 생각이라 ㅋㅋ `foo`, `bar` 이런건 좀 의미 없는 이름이다 보니까 스콥드 슬롯의 문제점이나 컴포넌트 명에서 주는 코드 위계가 필요한 상황에서 좀 더 코드가 아니라 본문의 설명에 의지해야 하는 것 같아요. 그래서 가급적 특정 개념을 설명할 때 코드가 들어가면 해당 코드의 이름 하나 하나가 좀 더 의미 있는게 어떨까 하는 제 개인적인 의견이에요 :) 요건 지금 글에서 모두 반영하면 수정해야 할 양이 많아서 다음 글부터 요런 부분도 참고해 보시면 어떨까 해서 말씀 드렸습니다 :) 👍 👍 👍 😄

2021-09-11 05:49 UTC, joshua1988 approved these changes

2021-09-11 06:00 UTC, merged